// Generated by Bisonc++ V6.00.00 on Sat, 17 Mar 2018 16:54:24 +0100

// base/comment

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved__::UNDETERMINED__, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok__
// which is applied. In this errTok__ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved__
    {
        UNDETERMINED__   = -2,
        EOF__            = -1,
        errTok__         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    enum StateTransition
    {
        ACCEPT__   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {305, 1}, // 1: start ->  command_list
     {306, 2}, // 2: command_list ->  command command_list
     {306, 0}, // 3: command_list ->  <empty>
     {307, 1}, // 4: command ->  expression
     {307, 1}, // 5: command ->  assign
     {307, 3}, // 6: command (OPARENTHESIS) ->  OPARENTHESIS command_list CPARENTHESIS
     {307, 3}, // 7: command (OCURLY) ->  OCURLY command_list CCURLY
     {307, 5}, // 8: command (KEYWORD_FOR) ->  KEYWORD_FOR condition KEYWORD_DO command_list KEYWORD_DONE
     {307, 7}, // 9: command (KEYWORD_FOR) ->  KEYWORD_FOR IDENTIFIER KEYWORD_IN expression KEYWORD_DO command_list KEYWORD_DONE
     {307, 11}, // 10: command (KEYWORD_FOR) ->  KEYWORD_FOR OPARENTHESIS assign COMMAND_SEPARATOR expression COMMAND_SEPARATOR expression CPARENTHESIS KEYWORD_DO command_list KEYWORD_DONE
     {307, 5}, // 11: command (KEYWORD_WHILE) ->  KEYWORD_WHILE condition KEYWORD_DO command_list KEYWORD_DONE
     {307, 5}, // 12: command (KEYWORD_UNTIL) ->  KEYWORD_UNTIL condition KEYWORD_DO command_list KEYWORD_DONE
     {307, 5}, // 13: command (KEYWORD_CASE) ->  KEYWORD_CASE expression KEYWORD_IN caseparts KEYWORD_ESAC
     {307, 6}, // 14: command (KEYWORD_IF) ->  KEYWORD_IF condition KEYWORD_THEN command_list else_part KEYWORD_FI
     {310, 1}, // 15: condition ->  expression
     {310, 2}, // 16: condition (NEGATE) ->  NEGATE expression
     {308, 3}, // 17: expression (OPERATOR_AND) ->  expression OPERATOR_AND expression
     {308, 3}, // 18: expression (OPERATOR_OR) ->  expression OPERATOR_OR expression
     {308, 3}, // 19: expression (OPERATOR_EQUAL) ->  expression OPERATOR_EQUAL expression
     {308, 3}, // 20: expression (OPERATOR_NOT_EQUAL) ->  expression OPERATOR_NOT_EQUAL expression
     {308, 3}, // 21: expression (OPERATOR_LESS_EQUAL) ->  expression OPERATOR_LESS_EQUAL expression
     {308, 3}, // 22: expression (OPERATOR_GREATER_EQUAL) ->  expression OPERATOR_GREATER_EQUAL expression
     {308, 3}, // 23: expression (OPERATOR_LESS_THAN) ->  expression OPERATOR_LESS_THAN expression
     {308, 3}, // 24: expression (OPERATOR_GREATER_THAN) ->  expression OPERATOR_GREATER_THAN expression
     {308, 3}, // 25: expression (OPERATOR_PLUS) ->  expression OPERATOR_PLUS expression
     {308, 3}, // 26: expression (OPERATOR_MINUS) ->  expression OPERATOR_MINUS expression
     {308, 3}, // 27: expression (OPERATOR_MULTIPLICATION) ->  expression OPERATOR_MULTIPLICATION expression
     {308, 3}, // 28: expression (OPERATOR_DIVISION) ->  expression OPERATOR_DIVISION expression
     {308, 3}, // 29: expression (OPERATOR_MODULO) ->  expression OPERATOR_MODULO expression
     {308, 3}, // 30: expression (OPERATOR_POWER) ->  expression OPERATOR_POWER expression
     {308, 1}, // 31: expression (INTEGER) ->  INTEGER
     {308, 1}, // 32: expression (FLOAT) ->  FLOAT
     {308, 1}, // 33: expression (SINGLEQUOTE) ->  SINGLEQUOTE
     {308, 1}, // 34: expression (DOUBLEQUOTE) ->  DOUBLEQUOTE
     {308, 1}, // 35: expression ->  input_output
     {308, 1}, // 36: expression (IDENTIFIER) ->  IDENTIFIER
     {313, 2}, // 37: input_output (OUTPUT_CREATION) ->  OUTPUT_CREATION IDENTIFIER
     {313, 2}, // 38: input_output (INPUT_REDIRECTION) ->  INPUT_REDIRECTION IDENTIFIER
     {313, 2}, // 39: input_output (INPUT_FROM_A_HERE_DOCUMENT) ->  INPUT_FROM_A_HERE_DOCUMENT IDENTIFIER
     {313, 2}, // 40: input_output (OUTPUT_APPEND) ->  OUTPUT_APPEND IDENTIFIER
     {309, 3}, // 41: assign (IDENTIFIER) ->  IDENTIFIER OPERATOR_LET_BE expression
     {311, 2}, // 42: caseparts ->  case_part caseparts2
     {315, 2}, // 43: caseparts2 ->  case_part caseparts2
     {315, 0}, // 44: caseparts2 ->  <empty>
     {314, 4}, // 45: case_part (CCURLY) ->  pattern CCURLY command_list CASE_DELIMITER
     {312, 5}, // 46: else_part (KEYWORD_ELIF) ->  KEYWORD_ELIF condition KEYWORD_THEN command_list else_part
     {312, 2}, // 47: else_part (KEYWORD_ELSE) ->  KEYWORD_ELSE command_list
     {312, 0}, // 48: else_part ->  <empty>
     {316, 1}, // 49: pattern (IDENTIFIER) ->  IDENTIFIER
     {316, 3}, // 50: pattern (PIPE_SYMBOL) ->  pattern PIPE_SYMBOL IDENTIFIER
     {317, 1}, // 51: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_DEF}, { 23} },                              
    { {     305}, {  1} }, // start                     
    { {     306}, {  2} }, // command_list              
    { {     307}, {  3} }, // command                   
    { {     308}, {  4} }, // expression                
    { {     309}, {  5} }, // assign                    
    { {     278}, {  6} }, // OPARENTHESIS              
    { {     270}, {  7} }, // OCURLY                    
    { {     265}, {  8} }, // KEYWORD_FOR               
    { {     266}, {  9} }, // KEYWORD_WHILE             
    { {     267}, { 10} }, // KEYWORD_UNTIL             
    { {     262}, { 11} }, // KEYWORD_CASE              
    { {     257}, { 12} }, // KEYWORD_IF                
    { {     287}, { 13} }, // INTEGER                   
    { {     286}, { 14} }, // FLOAT                     
    { {     284}, { 15} }, // SINGLEQUOTE               
    { {     285}, { 16} }, // DOUBLEQUOTE               
    { {     313}, { 17} }, // input_output              
    { {     288}, { 18} }, // IDENTIFIER                
    { {     282}, { 19} }, // OUTPUT_CREATION           
    { {     280}, { 20} }, // INPUT_REDIRECTION         
    { {     281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, { 22} }, // OUTPUT_APPEND             
    { {       0}, { -3} },                              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {        2} }, 
    { {     EOF__}, { ACCEPT__} }, 
    { {         0}, {        0} }, 
};

SR__ s_2[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_3[] =
{
    { { REQ_DEF}, { 22} },                              
    { {     306}, { 23} }, // command_list              
    { {     307}, {  3} }, // command                   
    { {     308}, {  4} }, // expression                
    { {     309}, {  5} }, // assign                    
    { {     278}, {  6} }, // OPARENTHESIS              
    { {     270}, {  7} }, // OCURLY                    
    { {     265}, {  8} }, // KEYWORD_FOR               
    { {     266}, {  9} }, // KEYWORD_WHILE             
    { {     267}, { 10} }, // KEYWORD_UNTIL             
    { {     262}, { 11} }, // KEYWORD_CASE              
    { {     257}, { 12} }, // KEYWORD_IF                
    { {     287}, { 13} }, // INTEGER                   
    { {     286}, { 14} }, // FLOAT                     
    { {     284}, { 15} }, // SINGLEQUOTE               
    { {     285}, { 16} }, // DOUBLEQUOTE               
    { {     313}, { 17} }, // input_output              
    { {     288}, { 18} }, // IDENTIFIER                
    { {     282}, { 19} }, // OUTPUT_CREATION           
    { {     280}, { 20} }, // INPUT_REDIRECTION         
    { {     281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, { 22} }, // OUTPUT_APPEND             
    { {       0}, { -3} },                              
};

SR__ s_4[] =
{
    { { REQ_DEF}, { 15} },                           
    { {     291}, { 24} }, // OPERATOR_AND           
    { {     292}, { 25} }, // OPERATOR_OR            
    { {     293}, { 26} }, // OPERATOR_EQUAL         
    { {     298}, { 27} }, // OPERATOR_NOT_EQUAL     
    { {     297}, { 28} }, // OPERATOR_LESS_EQUAL    
    { {     296}, { 29} }, // OPERATOR_GREATER_EQUAL 
    { {     295}, { 30} }, // OPERATOR_LESS_THAN     
    { {     294}, { 31} }, // OPERATOR_GREATER_THAN  
    { {     299}, { 32} }, // OPERATOR_PLUS          
    { {     300}, { 33} }, // OPERATOR_MINUS         
    { {     301}, { 34} }, // OPERATOR_MULTIPLICATION
    { {     302}, { 35} }, // OPERATOR_DIVISION      
    { {     303}, { 36} }, // OPERATOR_MODULO        
    { {     304}, { 37} }, // OPERATOR_POWER         
    { {       0}, { -4} },                           
};

SR__ s_5[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_6[] =
{
    { { REQ_DEF}, { 22} },                              
    { {     306}, { 38} }, // command_list              
    { {     307}, {  3} }, // command                   
    { {     308}, {  4} }, // expression                
    { {     309}, {  5} }, // assign                    
    { {     278}, {  6} }, // OPARENTHESIS              
    { {     270}, {  7} }, // OCURLY                    
    { {     265}, {  8} }, // KEYWORD_FOR               
    { {     266}, {  9} }, // KEYWORD_WHILE             
    { {     267}, { 10} }, // KEYWORD_UNTIL             
    { {     262}, { 11} }, // KEYWORD_CASE              
    { {     257}, { 12} }, // KEYWORD_IF                
    { {     287}, { 13} }, // INTEGER                   
    { {     286}, { 14} }, // FLOAT                     
    { {     284}, { 15} }, // SINGLEQUOTE               
    { {     285}, { 16} }, // DOUBLEQUOTE               
    { {     313}, { 17} }, // input_output              
    { {     288}, { 18} }, // IDENTIFIER                
    { {     282}, { 19} }, // OUTPUT_CREATION           
    { {     280}, { 20} }, // INPUT_REDIRECTION         
    { {     281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, { 22} }, // OUTPUT_APPEND             
    { {       0}, { -3} },                              
};

SR__ s_7[] =
{
    { { REQ_DEF}, { 22} },                              
    { {     306}, { 39} }, // command_list              
    { {     307}, {  3} }, // command                   
    { {     308}, {  4} }, // expression                
    { {     309}, {  5} }, // assign                    
    { {     278}, {  6} }, // OPARENTHESIS              
    { {     270}, {  7} }, // OCURLY                    
    { {     265}, {  8} }, // KEYWORD_FOR               
    { {     266}, {  9} }, // KEYWORD_WHILE             
    { {     267}, { 10} }, // KEYWORD_UNTIL             
    { {     262}, { 11} }, // KEYWORD_CASE              
    { {     257}, { 12} }, // KEYWORD_IF                
    { {     287}, { 13} }, // INTEGER                   
    { {     286}, { 14} }, // FLOAT                     
    { {     284}, { 15} }, // SINGLEQUOTE               
    { {     285}, { 16} }, // DOUBLEQUOTE               
    { {     313}, { 17} }, // input_output              
    { {     288}, { 18} }, // IDENTIFIER                
    { {     282}, { 19} }, // OUTPUT_CREATION           
    { {     280}, { 20} }, // INPUT_REDIRECTION         
    { {     281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, { 22} }, // OUTPUT_APPEND             
    { {       0}, { -3} },                              
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, { 15} },                              
    { {       310}, { 40} }, // condition                 
    { {       288}, { 41} }, // IDENTIFIER                
    { {       278}, { 42} }, // OPARENTHESIS              
    { {       308}, { 43} }, // expression                
    { {       290}, { 44} }, // NEGATE                    
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, { 14} },                              
    { {       310}, { 45} }, // condition                 
    { {       308}, { 43} }, // expression                
    { {       290}, { 44} }, // NEGATE                    
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, { 14} },                              
    { {       310}, { 47} }, // condition                 
    { {       308}, { 43} }, // expression                
    { {       290}, { 44} }, // NEGATE                    
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 48} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, { 14} },                              
    { {       310}, { 49} }, // condition                 
    { {       308}, { 43} }, // expression                
    { {       290}, { 44} }, // NEGATE                    
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_15[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -34} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_18[] =
{
    { { REQ_DEF}, {   2} },                   
    { {     289}, {  50} }, // OPERATOR_LET_BE
    { {       0}, { -36} },                   
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       288}, { 51} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       288}, { 52} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       288}, { 53} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       288}, { 54} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_23[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 55} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 56} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 57} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 58} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 59} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 60} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 61} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 62} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 63} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 64} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 65} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 66} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 67} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 68} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       279}, { 69} }, // CPARENTHESIS
    { {         0}, {  0} },                
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       271}, { 70} }, // CCURLY
    { {         0}, {  0} },          
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       268}, { 71} }, // KEYWORD_DO
    { {         0}, {  0} },              
};

SR__ s_41[] =
{
    { { REQ_DEF}, {   2} },              
    { {     263}, {  72} }, // KEYWORD_IN
    { {       0}, { -36} },              
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       309}, { 73} }, // assign    
    { {       288}, { 74} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_43[] =
{
    { { REQ_DEF}, {  15} },                           
    { {     291}, {  24} }, // OPERATOR_AND           
    { {     292}, {  25} }, // OPERATOR_OR            
    { {     293}, {  26} }, // OPERATOR_EQUAL         
    { {     298}, {  27} }, // OPERATOR_NOT_EQUAL     
    { {     297}, {  28} }, // OPERATOR_LESS_EQUAL    
    { {     296}, {  29} }, // OPERATOR_GREATER_EQUAL 
    { {     295}, {  30} }, // OPERATOR_LESS_THAN     
    { {     294}, {  31} }, // OPERATOR_GREATER_THAN  
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -15} },                           
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 75} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       268}, { 76} }, // KEYWORD_DO
    { {         0}, {  0} },              
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       268}, { 77} }, // KEYWORD_DO
    { {         0}, {  0} },              
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, { 16} },                           
    { {       263}, { 78} }, // KEYWORD_IN             
    { {       291}, { 24} }, // OPERATOR_AND           
    { {       292}, { 25} }, // OPERATOR_OR            
    { {       293}, { 26} }, // OPERATOR_EQUAL         
    { {       298}, { 27} }, // OPERATOR_NOT_EQUAL     
    { {       297}, { 28} }, // OPERATOR_LESS_EQUAL    
    { {       296}, { 29} }, // OPERATOR_GREATER_EQUAL 
    { {       295}, { 30} }, // OPERATOR_LESS_THAN     
    { {       294}, { 31} }, // OPERATOR_GREATER_THAN  
    { {       299}, { 32} }, // OPERATOR_PLUS          
    { {       300}, { 33} }, // OPERATOR_MINUS         
    { {       301}, { 34} }, // OPERATOR_MULTIPLICATION
    { {       302}, { 35} }, // OPERATOR_DIVISION      
    { {       303}, { 36} }, // OPERATOR_MODULO        
    { {       304}, { 37} }, // OPERATOR_POWER         
    { {         0}, {  0} },                           
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       258}, { 79} }, // KEYWORD_THEN
    { {         0}, {  0} },                
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 80} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_53[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -39} }, 
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -40} }, 
};

SR__ s_55[] =
{
    { { REQ_DEF}, {  13} },                           
    { {     293}, {  26} }, // OPERATOR_EQUAL         
    { {     298}, {  27} }, // OPERATOR_NOT_EQUAL     
    { {     297}, {  28} }, // OPERATOR_LESS_EQUAL    
    { {     296}, {  29} }, // OPERATOR_GREATER_EQUAL 
    { {     295}, {  30} }, // OPERATOR_LESS_THAN     
    { {     294}, {  31} }, // OPERATOR_GREATER_THAN  
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -17} },                           
};

SR__ s_56[] =
{
    { { REQ_DEF}, {  13} },                           
    { {     293}, {  26} }, // OPERATOR_EQUAL         
    { {     298}, {  27} }, // OPERATOR_NOT_EQUAL     
    { {     297}, {  28} }, // OPERATOR_LESS_EQUAL    
    { {     296}, {  29} }, // OPERATOR_GREATER_EQUAL 
    { {     295}, {  30} }, // OPERATOR_LESS_THAN     
    { {     294}, {  31} }, // OPERATOR_GREATER_THAN  
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -18} },                           
};

SR__ s_57[] =
{
    { { REQ_DEF}, {   7} },                           
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -19} },                           
};

SR__ s_58[] =
{
    { { REQ_DEF}, {   7} },                           
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -20} },                           
};

SR__ s_59[] =
{
    { { REQ_DEF}, {   7} },                           
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -21} },                           
};

SR__ s_60[] =
{
    { { REQ_DEF}, {   7} },                           
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -22} },                           
};

SR__ s_61[] =
{
    { { REQ_DEF}, {   7} },                           
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -23} },                           
};

SR__ s_62[] =
{
    { { REQ_DEF}, {   7} },                           
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -24} },                           
};

SR__ s_63[] =
{
    { { REQ_DEF}, {   5} },                           
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -25} },                           
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   5} },                           
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -26} },                           
};

SR__ s_65[] =
{
    { { REQ_DEF}, {   2} },                  
    { {     304}, {  37} }, // OPERATOR_POWER
    { {       0}, { -27} },                  
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   2} },                  
    { {     304}, {  37} }, // OPERATOR_POWER
    { {       0}, { -28} },                  
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   2} },                  
    { {     304}, {  37} }, // OPERATOR_POWER
    { {       0}, { -29} },                  
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_69[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_70[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_71[] =
{
    { { REQ_DEF}, { 22} },                              
    { {     306}, { 81} }, // command_list              
    { {     307}, {  3} }, // command                   
    { {     308}, {  4} }, // expression                
    { {     309}, {  5} }, // assign                    
    { {     278}, {  6} }, // OPARENTHESIS              
    { {     270}, {  7} }, // OCURLY                    
    { {     265}, {  8} }, // KEYWORD_FOR               
    { {     266}, {  9} }, // KEYWORD_WHILE             
    { {     267}, { 10} }, // KEYWORD_UNTIL             
    { {     262}, { 11} }, // KEYWORD_CASE              
    { {     257}, { 12} }, // KEYWORD_IF                
    { {     287}, { 13} }, // INTEGER                   
    { {     286}, { 14} }, // FLOAT                     
    { {     284}, { 15} }, // SINGLEQUOTE               
    { {     285}, { 16} }, // DOUBLEQUOTE               
    { {     313}, { 17} }, // input_output              
    { {     288}, { 18} }, // IDENTIFIER                
    { {     282}, { 19} }, // OUTPUT_CREATION           
    { {     280}, { 20} }, // INPUT_REDIRECTION         
    { {     281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, { 22} }, // OUTPUT_APPEND             
    { {       0}, { -3} },                              
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 82} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  2} },                     
    { {       275}, { 83} }, // COMMAND_SEPARATOR
    { {         0}, {  0} },                     
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  2} },                   
    { {       289}, { 50} }, // OPERATOR_LET_BE
    { {         0}, {  0} },                   
};

SR__ s_75[] =
{
    { { REQ_DEF}, {  15} },                           
    { {     291}, {  24} }, // OPERATOR_AND           
    { {     292}, {  25} }, // OPERATOR_OR            
    { {     293}, {  26} }, // OPERATOR_EQUAL         
    { {     298}, {  27} }, // OPERATOR_NOT_EQUAL     
    { {     297}, {  28} }, // OPERATOR_LESS_EQUAL    
    { {     296}, {  29} }, // OPERATOR_GREATER_EQUAL 
    { {     295}, {  30} }, // OPERATOR_LESS_THAN     
    { {     294}, {  31} }, // OPERATOR_GREATER_THAN  
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -16} },                           
};

SR__ s_76[] =
{
    { { REQ_DEF}, { 22} },                              
    { {     306}, { 84} }, // command_list              
    { {     307}, {  3} }, // command                   
    { {     308}, {  4} }, // expression                
    { {     309}, {  5} }, // assign                    
    { {     278}, {  6} }, // OPARENTHESIS              
    { {     270}, {  7} }, // OCURLY                    
    { {     265}, {  8} }, // KEYWORD_FOR               
    { {     266}, {  9} }, // KEYWORD_WHILE             
    { {     267}, { 10} }, // KEYWORD_UNTIL             
    { {     262}, { 11} }, // KEYWORD_CASE              
    { {     257}, { 12} }, // KEYWORD_IF                
    { {     287}, { 13} }, // INTEGER                   
    { {     286}, { 14} }, // FLOAT                     
    { {     284}, { 15} }, // SINGLEQUOTE               
    { {     285}, { 16} }, // DOUBLEQUOTE               
    { {     313}, { 17} }, // input_output              
    { {     288}, { 18} }, // IDENTIFIER                
    { {     282}, { 19} }, // OUTPUT_CREATION           
    { {     280}, { 20} }, // INPUT_REDIRECTION         
    { {     281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, { 22} }, // OUTPUT_APPEND             
    { {       0}, { -3} },                              
};

SR__ s_77[] =
{
    { { REQ_DEF}, { 22} },                              
    { {     306}, { 85} }, // command_list              
    { {     307}, {  3} }, // command                   
    { {     308}, {  4} }, // expression                
    { {     309}, {  5} }, // assign                    
    { {     278}, {  6} }, // OPARENTHESIS              
    { {     270}, {  7} }, // OCURLY                    
    { {     265}, {  8} }, // KEYWORD_FOR               
    { {     266}, {  9} }, // KEYWORD_WHILE             
    { {     267}, { 10} }, // KEYWORD_UNTIL             
    { {     262}, { 11} }, // KEYWORD_CASE              
    { {     257}, { 12} }, // KEYWORD_IF                
    { {     287}, { 13} }, // INTEGER                   
    { {     286}, { 14} }, // FLOAT                     
    { {     284}, { 15} }, // SINGLEQUOTE               
    { {     285}, { 16} }, // DOUBLEQUOTE               
    { {     313}, { 17} }, // input_output              
    { {     288}, { 18} }, // IDENTIFIER                
    { {     282}, { 19} }, // OUTPUT_CREATION           
    { {     280}, { 20} }, // INPUT_REDIRECTION         
    { {     281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, { 22} }, // OUTPUT_APPEND             
    { {       0}, { -3} },                              
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  5} },              
    { {       311}, { 86} }, // caseparts 
    { {       314}, { 87} }, // case_part 
    { {       316}, { 88} }, // pattern   
    { {       288}, { 89} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_79[] =
{
    { { REQ_DEF}, { 22} },                              
    { {     306}, { 90} }, // command_list              
    { {     307}, {  3} }, // command                   
    { {     308}, {  4} }, // expression                
    { {     309}, {  5} }, // assign                    
    { {     278}, {  6} }, // OPARENTHESIS              
    { {     270}, {  7} }, // OCURLY                    
    { {     265}, {  8} }, // KEYWORD_FOR               
    { {     266}, {  9} }, // KEYWORD_WHILE             
    { {     267}, { 10} }, // KEYWORD_UNTIL             
    { {     262}, { 11} }, // KEYWORD_CASE              
    { {     257}, { 12} }, // KEYWORD_IF                
    { {     287}, { 13} }, // INTEGER                   
    { {     286}, { 14} }, // FLOAT                     
    { {     284}, { 15} }, // SINGLEQUOTE               
    { {     285}, { 16} }, // DOUBLEQUOTE               
    { {     313}, { 17} }, // input_output              
    { {     288}, { 18} }, // IDENTIFIER                
    { {     282}, { 19} }, // OUTPUT_CREATION           
    { {     280}, { 20} }, // INPUT_REDIRECTION         
    { {     281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, { 22} }, // OUTPUT_APPEND             
    { {       0}, { -3} },                              
};

SR__ s_80[] =
{
    { { REQ_DEF}, {  15} },                           
    { {     291}, {  24} }, // OPERATOR_AND           
    { {     292}, {  25} }, // OPERATOR_OR            
    { {     293}, {  26} }, // OPERATOR_EQUAL         
    { {     298}, {  27} }, // OPERATOR_NOT_EQUAL     
    { {     297}, {  28} }, // OPERATOR_LESS_EQUAL    
    { {     296}, {  29} }, // OPERATOR_GREATER_EQUAL 
    { {     295}, {  30} }, // OPERATOR_LESS_THAN     
    { {     294}, {  31} }, // OPERATOR_GREATER_THAN  
    { {     299}, {  32} }, // OPERATOR_PLUS          
    { {     300}, {  33} }, // OPERATOR_MINUS         
    { {     301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {     302}, {  35} }, // OPERATOR_DIVISION      
    { {     303}, {  36} }, // OPERATOR_MODULO        
    { {     304}, {  37} }, // OPERATOR_POWER         
    { {       0}, { -41} },                           
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       269}, { 91} }, // KEYWORD_DONE
    { {         0}, {  0} },                
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, { 16} },                           
    { {       268}, { 92} }, // KEYWORD_DO             
    { {       291}, { 24} }, // OPERATOR_AND           
    { {       292}, { 25} }, // OPERATOR_OR            
    { {       293}, { 26} }, // OPERATOR_EQUAL         
    { {       298}, { 27} }, // OPERATOR_NOT_EQUAL     
    { {       297}, { 28} }, // OPERATOR_LESS_EQUAL    
    { {       296}, { 29} }, // OPERATOR_GREATER_EQUAL 
    { {       295}, { 30} }, // OPERATOR_LESS_THAN     
    { {       294}, { 31} }, // OPERATOR_GREATER_THAN  
    { {       299}, { 32} }, // OPERATOR_PLUS          
    { {       300}, { 33} }, // OPERATOR_MINUS         
    { {       301}, { 34} }, // OPERATOR_MULTIPLICATION
    { {       302}, { 35} }, // OPERATOR_DIVISION      
    { {       303}, { 36} }, // OPERATOR_MODULO        
    { {       304}, { 37} }, // OPERATOR_POWER         
    { {         0}, {  0} },                           
};

SR__ s_83[] =
{
    { { REQ_TOKEN}, { 12} },                              
    { {       308}, { 93} }, // expression                
    { {       287}, { 13} }, // INTEGER                   
    { {       286}, { 14} }, // FLOAT                     
    { {       284}, { 15} }, // SINGLEQUOTE               
    { {       285}, { 16} }, // DOUBLEQUOTE               
    { {       313}, { 17} }, // input_output              
    { {       288}, { 46} }, // IDENTIFIER                
    { {       282}, { 19} }, // OUTPUT_CREATION           
    { {       280}, { 20} }, // INPUT_REDIRECTION         
    { {       281}, { 21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, { 22} }, // OUTPUT_APPEND             
    { {         0}, {  0} },                              
};

SR__ s_84[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       269}, { 94} }, // KEYWORD_DONE
    { {         0}, {  0} },                
};

SR__ s_85[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       269}, { 95} }, // KEYWORD_DONE
    { {         0}, {  0} },                
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       264}, { 96} }, // KEYWORD_ESAC
    { {         0}, {  0} },                
};

SR__ s_87[] =
{
    { { REQ_DEF}, {   5} },              
    { {     315}, {  97} }, // caseparts2
    { {     314}, {  98} }, // case_part 
    { {     316}, {  88} }, // pattern   
    { {     288}, {  89} }, // IDENTIFIER
    { {       0}, { -44} },              
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {   3} },               
    { {       271}, {  99} }, // CCURLY     
    { {       272}, { 100} }, // PIPE_SYMBOL
    { {         0}, {   0} },               
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   4} },                
    { {     312}, { 101} }, // else_part   
    { {     260}, { 102} }, // KEYWORD_ELIF
    { {     259}, { 103} }, // KEYWORD_ELSE
    { {       0}, { -48} },                
};

SR__ s_91[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_92[] =
{
    { { REQ_DEF}, {  22} },                              
    { {     306}, { 104} }, // command_list              
    { {     307}, {   3} }, // command                   
    { {     308}, {   4} }, // expression                
    { {     309}, {   5} }, // assign                    
    { {     278}, {   6} }, // OPARENTHESIS              
    { {     270}, {   7} }, // OCURLY                    
    { {     265}, {   8} }, // KEYWORD_FOR               
    { {     266}, {   9} }, // KEYWORD_WHILE             
    { {     267}, {  10} }, // KEYWORD_UNTIL             
    { {     262}, {  11} }, // KEYWORD_CASE              
    { {     257}, {  12} }, // KEYWORD_IF                
    { {     287}, {  13} }, // INTEGER                   
    { {     286}, {  14} }, // FLOAT                     
    { {     284}, {  15} }, // SINGLEQUOTE               
    { {     285}, {  16} }, // DOUBLEQUOTE               
    { {     313}, {  17} }, // input_output              
    { {     288}, {  18} }, // IDENTIFIER                
    { {     282}, {  19} }, // OUTPUT_CREATION           
    { {     280}, {  20} }, // INPUT_REDIRECTION         
    { {     281}, {  21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, {  22} }, // OUTPUT_APPEND             
    { {       0}, {  -3} },                              
};

SR__ s_93[] =
{
    { { REQ_TOKEN}, {  16} },                           
    { {       275}, { 105} }, // COMMAND_SEPARATOR      
    { {       291}, {  24} }, // OPERATOR_AND           
    { {       292}, {  25} }, // OPERATOR_OR            
    { {       293}, {  26} }, // OPERATOR_EQUAL         
    { {       298}, {  27} }, // OPERATOR_NOT_EQUAL     
    { {       297}, {  28} }, // OPERATOR_LESS_EQUAL    
    { {       296}, {  29} }, // OPERATOR_GREATER_EQUAL 
    { {       295}, {  30} }, // OPERATOR_LESS_THAN     
    { {       294}, {  31} }, // OPERATOR_GREATER_THAN  
    { {       299}, {  32} }, // OPERATOR_PLUS          
    { {       300}, {  33} }, // OPERATOR_MINUS         
    { {       301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {       302}, {  35} }, // OPERATOR_DIVISION      
    { {       303}, {  36} }, // OPERATOR_MODULO        
    { {       304}, {  37} }, // OPERATOR_POWER         
    { {         0}, {   0} },                           
};

SR__ s_94[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_95[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_96[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_97[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_98[] =
{
    { { REQ_DEF}, {   5} },              
    { {     315}, { 106} }, // caseparts2
    { {     314}, {  98} }, // case_part 
    { {     316}, {  88} }, // pattern   
    { {     288}, {  89} }, // IDENTIFIER
    { {       0}, { -44} },              
};

SR__ s_99[] =
{
    { { REQ_DEF}, {  22} },                              
    { {     306}, { 107} }, // command_list              
    { {     307}, {   3} }, // command                   
    { {     308}, {   4} }, // expression                
    { {     309}, {   5} }, // assign                    
    { {     278}, {   6} }, // OPARENTHESIS              
    { {     270}, {   7} }, // OCURLY                    
    { {     265}, {   8} }, // KEYWORD_FOR               
    { {     266}, {   9} }, // KEYWORD_WHILE             
    { {     267}, {  10} }, // KEYWORD_UNTIL             
    { {     262}, {  11} }, // KEYWORD_CASE              
    { {     257}, {  12} }, // KEYWORD_IF                
    { {     287}, {  13} }, // INTEGER                   
    { {     286}, {  14} }, // FLOAT                     
    { {     284}, {  15} }, // SINGLEQUOTE               
    { {     285}, {  16} }, // DOUBLEQUOTE               
    { {     313}, {  17} }, // input_output              
    { {     288}, {  18} }, // IDENTIFIER                
    { {     282}, {  19} }, // OUTPUT_CREATION           
    { {     280}, {  20} }, // INPUT_REDIRECTION         
    { {     281}, {  21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, {  22} }, // OUTPUT_APPEND             
    { {       0}, {  -3} },                              
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       288}, { 108} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       261}, { 109} }, // KEYWORD_FI
    { {         0}, {   0} },              
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {  14} },                              
    { {       310}, { 110} }, // condition                 
    { {       308}, {  43} }, // expression                
    { {       290}, {  44} }, // NEGATE                    
    { {       287}, {  13} }, // INTEGER                   
    { {       286}, {  14} }, // FLOAT                     
    { {       284}, {  15} }, // SINGLEQUOTE               
    { {       285}, {  16} }, // DOUBLEQUOTE               
    { {       313}, {  17} }, // input_output              
    { {       288}, {  46} }, // IDENTIFIER                
    { {       282}, {  19} }, // OUTPUT_CREATION           
    { {       280}, {  20} }, // INPUT_REDIRECTION         
    { {       281}, {  21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, {  22} }, // OUTPUT_APPEND             
    { {         0}, {   0} },                              
};

SR__ s_103[] =
{
    { { REQ_DEF}, {  22} },                              
    { {     306}, { 111} }, // command_list              
    { {     307}, {   3} }, // command                   
    { {     308}, {   4} }, // expression                
    { {     309}, {   5} }, // assign                    
    { {     278}, {   6} }, // OPARENTHESIS              
    { {     270}, {   7} }, // OCURLY                    
    { {     265}, {   8} }, // KEYWORD_FOR               
    { {     266}, {   9} }, // KEYWORD_WHILE             
    { {     267}, {  10} }, // KEYWORD_UNTIL             
    { {     262}, {  11} }, // KEYWORD_CASE              
    { {     257}, {  12} }, // KEYWORD_IF                
    { {     287}, {  13} }, // INTEGER                   
    { {     286}, {  14} }, // FLOAT                     
    { {     284}, {  15} }, // SINGLEQUOTE               
    { {     285}, {  16} }, // DOUBLEQUOTE               
    { {     313}, {  17} }, // input_output              
    { {     288}, {  18} }, // IDENTIFIER                
    { {     282}, {  19} }, // OUTPUT_CREATION           
    { {     280}, {  20} }, // INPUT_REDIRECTION         
    { {     281}, {  21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, {  22} }, // OUTPUT_APPEND             
    { {       0}, {  -3} },                              
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {   2} },                
    { {       269}, { 112} }, // KEYWORD_DONE
    { {         0}, {   0} },                
};

SR__ s_105[] =
{
    { { REQ_TOKEN}, {  12} },                              
    { {       308}, { 113} }, // expression                
    { {       287}, {  13} }, // INTEGER                   
    { {       286}, {  14} }, // FLOAT                     
    { {       284}, {  15} }, // SINGLEQUOTE               
    { {       285}, {  16} }, // DOUBLEQUOTE               
    { {       313}, {  17} }, // input_output              
    { {       288}, {  46} }, // IDENTIFIER                
    { {       282}, {  19} }, // OUTPUT_CREATION           
    { {       280}, {  20} }, // INPUT_REDIRECTION         
    { {       281}, {  21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       283}, {  22} }, // OUTPUT_APPEND             
    { {         0}, {   0} },                              
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_107[] =
{
    { { REQ_TOKEN}, {   2} },                  
    { {       276}, { 114} }, // CASE_DELIMITER
    { {         0}, {   0} },                  
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_109[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {   2} },                
    { {       258}, { 115} }, // KEYWORD_THEN
    { {         0}, {   0} },                
};

SR__ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_112[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {  16} },                           
    { {       279}, { 116} }, // CPARENTHESIS           
    { {       291}, {  24} }, // OPERATOR_AND           
    { {       292}, {  25} }, // OPERATOR_OR            
    { {       293}, {  26} }, // OPERATOR_EQUAL         
    { {       298}, {  27} }, // OPERATOR_NOT_EQUAL     
    { {       297}, {  28} }, // OPERATOR_LESS_EQUAL    
    { {       296}, {  29} }, // OPERATOR_GREATER_EQUAL 
    { {       295}, {  30} }, // OPERATOR_LESS_THAN     
    { {       294}, {  31} }, // OPERATOR_GREATER_THAN  
    { {       299}, {  32} }, // OPERATOR_PLUS          
    { {       300}, {  33} }, // OPERATOR_MINUS         
    { {       301}, {  34} }, // OPERATOR_MULTIPLICATION
    { {       302}, {  35} }, // OPERATOR_DIVISION      
    { {       303}, {  36} }, // OPERATOR_MODULO        
    { {       304}, {  37} }, // OPERATOR_POWER         
    { {         0}, {   0} },                           
};

SR__ s_114[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_115[] =
{
    { { REQ_DEF}, {  22} },                              
    { {     306}, { 117} }, // command_list              
    { {     307}, {   3} }, // command                   
    { {     308}, {   4} }, // expression                
    { {     309}, {   5} }, // assign                    
    { {     278}, {   6} }, // OPARENTHESIS              
    { {     270}, {   7} }, // OCURLY                    
    { {     265}, {   8} }, // KEYWORD_FOR               
    { {     266}, {   9} }, // KEYWORD_WHILE             
    { {     267}, {  10} }, // KEYWORD_UNTIL             
    { {     262}, {  11} }, // KEYWORD_CASE              
    { {     257}, {  12} }, // KEYWORD_IF                
    { {     287}, {  13} }, // INTEGER                   
    { {     286}, {  14} }, // FLOAT                     
    { {     284}, {  15} }, // SINGLEQUOTE               
    { {     285}, {  16} }, // DOUBLEQUOTE               
    { {     313}, {  17} }, // input_output              
    { {     288}, {  18} }, // IDENTIFIER                
    { {     282}, {  19} }, // OUTPUT_CREATION           
    { {     280}, {  20} }, // INPUT_REDIRECTION         
    { {     281}, {  21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, {  22} }, // OUTPUT_APPEND             
    { {       0}, {  -3} },                              
};

SR__ s_116[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       268}, { 118} }, // KEYWORD_DO
    { {         0}, {   0} },              
};

SR__ s_117[] =
{
    { { REQ_DEF}, {   4} },                
    { {     312}, { 119} }, // else_part   
    { {     260}, { 102} }, // KEYWORD_ELIF
    { {     259}, { 103} }, // KEYWORD_ELSE
    { {       0}, { -48} },                
};

SR__ s_118[] =
{
    { { REQ_DEF}, {  22} },                              
    { {     306}, { 120} }, // command_list              
    { {     307}, {   3} }, // command                   
    { {     308}, {   4} }, // expression                
    { {     309}, {   5} }, // assign                    
    { {     278}, {   6} }, // OPARENTHESIS              
    { {     270}, {   7} }, // OCURLY                    
    { {     265}, {   8} }, // KEYWORD_FOR               
    { {     266}, {   9} }, // KEYWORD_WHILE             
    { {     267}, {  10} }, // KEYWORD_UNTIL             
    { {     262}, {  11} }, // KEYWORD_CASE              
    { {     257}, {  12} }, // KEYWORD_IF                
    { {     287}, {  13} }, // INTEGER                   
    { {     286}, {  14} }, // FLOAT                     
    { {     284}, {  15} }, // SINGLEQUOTE               
    { {     285}, {  16} }, // DOUBLEQUOTE               
    { {     313}, {  17} }, // input_output              
    { {     288}, {  18} }, // IDENTIFIER                
    { {     282}, {  19} }, // OUTPUT_CREATION           
    { {     280}, {  20} }, // INPUT_REDIRECTION         
    { {     281}, {  21} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {     283}, {  22} }, // OUTPUT_APPEND             
    { {       0}, {  -3} },                              
};

SR__ s_119[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   2} },                
    { {       269}, { 121} }, // KEYWORD_DONE
    { {         0}, {   0} },                
};

SR__ s_121[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved__::UNDETERMINED__),
    // $insert baseclasscode
    d_requiredTokens__(0)
{
}

// base/clearin
void ParserBase::clearin__()
{
    d_nErrors__ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved__::UNDETERMINED__;
    d_next = TokenPair{ Reserved__::UNDETERMINED__, STYPE__{} };
    d_recovery = false;
    d_acceptedTokens__ = d_requiredTokens__;
    d_val__ = STYPE__{};

    push__(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

// base/lex
void ParserBase::lex__(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved__::EOF__;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup__() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR__ const *sr = s_state[d_state];
    SR__ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

}

// base/poptoken
void ParserBase::popToken__()
{
    d_token = d_next.first;
    d_val__ = std::move(d_next.second);

    d_next.first = Reserved__::UNDETERMINED__;
}

// base/push
void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize__() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val__) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken__(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val__) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken__()
{
    if (d_token != Reserved__::UNDETERMINED__)
        pushToken__(d_token);
}

// base/reduce
void ParserBase::reduce__(int rule)
{
    PI__ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop__(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift__(int action)
{
    push__(action);
    popToken__();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens__ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery__()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken__(Reserved__::errTok__);      // specify errTok__ as next token
    push__(lookup__());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top__() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery__()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle__ for details.

    startRecovery__();
}

// derived/executeaction
void Parser::executeAction__(int production)
try
{
    if (token__() != Reserved__::UNDETERMINED__)
        pushToken__(token__());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 53 "grammar"
        {
         std::cout << "command_list" << std::endl;
         }
        break;

        case 2:
#line 60 "grammar"
        {
         std::cout << "command command_list" << std::endl;
         }
        break;

        case 3:
#line 65 "grammar"
        {
         std::cout << "command_list -> empty" << std::endl;
         }
        break;

        case 4:
#line 72 "grammar"
        {
         std::cout << "expression" << std::endl;
         }
        break;

        case 5:
#line 77 "grammar"
        {
         std::cout << "assign" << std::endl;
         }
        break;

        case 6:
#line 82 "grammar"
        {
         std::cout << "OPARENTHESIS command_list CPARENTHESIS" << std::endl;
         }
        break;

        case 7:
#line 87 "grammar"
        {
         std::cout << "OCURLY command_list CCURLY" << std::endl;
         }
        break;

        case 8:
#line 92 "grammar"
        {
         std::cout << "KEYWORD_FOR condition KEYWORD_DO command_list KEYWORD_DONE" << std::endl;
         }
        break;

        case 9:
#line 97 "grammar"
        {
         std::cout << "KEYWORD_FOR IDENTIFIER KEYWORD_IN expression KEYWORD_DO command_list KEYWORD_DONE" << std::endl;
         }
        break;

        case 10:
#line 102 "grammar"
        {
         std::cout << "KEYWORD_FOR OPARENTHESIS assign COMMAND_SEPARATOR expression COMMAND_SEPARATOR expression CPARENTHESIS KEYWORD_DO command_list KEYWORD_DONE" << std::endl;
         }
        break;

        case 11:
#line 107 "grammar"
        {
         std::cout << "KEYWORD_WHILE condition KEYWORD_DO command_list KEYWORD_DONE" << std::endl;
         }
        break;

        case 12:
#line 112 "grammar"
        {
         std::cout << "KEYWORD_UNTIL condition KEYWORD_DO command_list KEYWORD_DONE" << std::endl;
         }
        break;

        case 13:
#line 117 "grammar"
        {
         std::cout << "KEYWORD_CASE expression KEYWORD_IN caseparts KEYWORD_ESAC" << std::endl;
         }
        break;

        case 14:
#line 122 "grammar"
        {
         std::cout << "KEYWORD_IF condition KEYWORD_THEN command_list else_part KEYWORD_FI" << std::endl;
         }
        break;

        case 15:
#line 129 "grammar"
        {
         std::cout << "expression" << std::endl;
         }
        break;

        case 16:
#line 134 "grammar"
        {
         std::cout << "NEGATE expression" << std::endl;
         }
        break;

        case 17:
#line 141 "grammar"
        {
         std::cout << "expression OPERATOR_AND expression" << std::endl;
         }
        break;

        case 18:
#line 146 "grammar"
        {
         std::cout << "expression OPERATOR_OR expression" << std::endl;
         }
        break;

        case 19:
#line 151 "grammar"
        {
         std::cout << "expression OPERATOR_EQUAL expression" << std::endl;
         }
        break;

        case 20:
#line 156 "grammar"
        {
         std::cout << "expression OPERATOR_NOT_EQUAL expression" << std::endl;
         }
        break;

        case 21:
#line 161 "grammar"
        {
         std::cout << "expression OPERATOR_LESS_EQUAL expression" << std::endl;
         }
        break;

        case 22:
#line 166 "grammar"
        {
         std::cout << "expression OPERATOR_GREATER_EQUAL expression" << std::endl;
         }
        break;

        case 23:
#line 171 "grammar"
        {
         std::cout << "expression OPERATOR_LESS_THAN expression" << std::endl;
         }
        break;

        case 24:
#line 176 "grammar"
        {
         std::cout << "expression OPERATOR_GREATER_THAN expression" << std::endl;
         }
        break;

        case 25:
#line 181 "grammar"
        {
         std::cout << "expression OPERATOR_PLUS expression" << std::endl;
         }
        break;

        case 26:
#line 186 "grammar"
        {
         std::cout << "expression OPERATOR_MINUS expression" << std::endl;
         }
        break;

        case 27:
#line 191 "grammar"
        {
         std::cout << "expression OPERATOR_MULTIPLICATION expression" << std::endl;
         }
        break;

        case 28:
#line 196 "grammar"
        {
         std::cout << "expression OPERATOR_DIVISION expression" << std::endl;
         }
        break;

        case 29:
#line 201 "grammar"
        {
         std::cout << "expression OPERATOR_MODULO expression" << std::endl;
         }
        break;

        case 30:
#line 206 "grammar"
        {
         std::cout << "expression OPERATOR_POWER expression" << std::endl;
         }
        break;

        case 31:
#line 211 "grammar"
        {
         std::cout << "INTEGER" << std::endl;
         }
        break;

        case 32:
#line 216 "grammar"
        {
         std::cout << "FLOAT" << std::endl;
         }
        break;

        case 33:
#line 221 "grammar"
        {
         std::cout << "SINGLEQUOTE" << std::endl;
         }
        break;

        case 34:
#line 226 "grammar"
        {
         std::cout << "DOUBLEQUOTE" << std::endl;
         }
        break;

        case 35:
#line 231 "grammar"
        {
         std::cout << "input_output" << std::endl;
         }
        break;

        case 36:
#line 236 "grammar"
        {
         std::cout << "IDENTIFIER" << std::endl;
         }
        break;

        case 37:
#line 244 "grammar"
        {
         std::cout << "OUTPUT_CREATION IDENTIFIER" << std::endl;
         }
        break;

        case 38:
#line 249 "grammar"
        {
         std::cout << "INPUT_REDIRECTION IDENTIFIER" << std::endl;
         }
        break;

        case 39:
#line 254 "grammar"
        {
         std::cout << "INPUT_FROM_A_HERE_DOCUMENT IDENTIFIER" << std::endl;
         }
        break;

        case 40:
#line 259 "grammar"
        {
         std::cout << "OUTPUT_APPEND IDENTIFIER" << std::endl;
         }
        break;

        case 41:
#line 268 "grammar"
        {
         std::cout << "IDENTIFIER OPERATOR_LET_BE expression" << std::endl;
         }
        break;

        case 42:
#line 275 "grammar"
        {
         std::cout << "case_part caseparts2" << std::endl;
         }
        break;

        case 43:
#line 282 "grammar"
        {
         std::cout << "case_part caseparts2" << std::endl;
         }
        break;

        case 44:
#line 287 "grammar"
        {
         std::cout << "caseparts2->empty" << std::endl;
         }
        break;

        case 45:
#line 294 "grammar"
        {
         std::cout << "pattern CCURLY command_list CASE_DELIMITER" << std::endl;
         }
        break;

        case 46:
#line 301 "grammar"
        {
         std::cout << "KEYWORD_ELIF condition KEYWORD_THEN command_list else_part" << std::endl;
         }
        break;

        case 47:
#line 306 "grammar"
        {
         std::cout << "KEYWORD_ELSE command_list" << std::endl;
         }
        break;

        case 48:
#line 311 "grammar"
        {
         std::cout << "else_part -> empty" << std::endl;
         }
        break;

        case 49:
#line 318 "grammar"
        {
         std::cout << "IDENTIFIER" << std::endl;
         }
        break;

        case 50:
#line 323 "grammar"
        {
         std::cout << "pattern PIPE_SYMBOL IDENTIFIER" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle__()
try
{
    if (s_state[state__()]->d_type & REQ_TOKEN)
        nextToken__();              // obtain next token


    int action = lookup__();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift__(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery__())
            redoToken__();
        else
            executeAction__(-action);
                                            // next token is the rule's LHS
        reduce__(-action); 
        return;
    }

    if (recovery__())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery__)
{
    if (not recovery__())
        errorRecovery__();
    else
    {
        if (token__() == Reserved__::EOF__)
            ABORT();
        popToken__();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken__()
{ 
    // If d_token is Reserved__::UNDETERMINED__ then if savedToken__() is
    // Reserved__::UNDETERMINED__ another token is obtained from lex(). Then
    // savedToken__() is assigned to d_token.

                                    // no need for a token: got one already
    if (token__() != Reserved__::UNDETERMINED__) 
    {
        return;                             
    }

    if (savedToken__() != Reserved__::UNDETERMINED__)
    {
        popToken__();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;       // accept another token (see
                                    // errorRecover())
        lex__(lex());
        print__();
    }
    print();
}

// derived/print
void Parser::print__()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin__.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin__();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle__();
    }
}
catch (Return__ retValue)
{
    return retValue or d_nErrors__;
}


// derived/tail


