// Generated by Bisonc++ V6.00.00 on Sun, 11 Mar 2018 18:18:40 +0100

// base/comment

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved__::UNDETERMINED__, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok__
// which is applied. In this errTok__ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved__
    {
        UNDETERMINED__   = -2,
        EOF__            = -1,
        errTok__         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    enum StateTransition
    {
        ACCEPT__   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {297, 1}, // 1: start ->  command_list
     {299, 1}, // 2: item (IDENTIFIER) ->  IDENTIFIER
     {299, 1}, // 3: item ->  input_output
     {299, 3}, // 4: item (IDENTIFIER) ->  IDENTIFIER OPERATOR_LET_BE value
     {301, 3}, // 5: value (OPERATOR_PLUS) ->  value OPERATOR_PLUS value
     {301, 3}, // 6: value (OPERATOR_MINUS) ->  value OPERATOR_MINUS value
     {301, 3}, // 7: value (OPERATOR_MULTIPLICATION) ->  value OPERATOR_MULTIPLICATION value
     {301, 3}, // 8: value (OPERATOR_DIVISION) ->  value OPERATOR_DIVISION value
     {301, 3}, // 9: value (OPERATOR_POWER) ->  value OPERATOR_POWER value
     {301, 3}, // 10: value (OPERATOR_MODULO) ->  value OPERATOR_MODULO value
     {301, 3}, // 11: value (OPERATOR_EQUALS) ->  value OPERATOR_EQUALS value
     {301, 3}, // 12: value (OPARENTHESIS) ->  OPARENTHESIS value CPARENTHESIS
     {301, 1}, // 13: value (FLOAT) ->  FLOAT
     {301, 1}, // 14: value (INTEGER) ->  INTEGER
     {301, 1}, // 15: value (SINGLEQUOTE) ->  SINGLEQUOTE
     {301, 1}, // 16: value (DOUBLEQUOTE) ->  DOUBLEQUOTE
     {301, 1}, // 17: value (IDENTIFIER) ->  IDENTIFIER
     {302, 1}, // 18: simple_command ->  item
     {302, 2}, // 19: simple_command ->  simple_command item
     {303, 1}, // 20: command ->  simple_command
     {303, 3}, // 21: command (OPARENTHESIS) ->  OPARENTHESIS command_list CPARENTHESIS
     {303, 3}, // 22: command (OCURLY) ->  OCURLY command_list CCURLY
     {303, 5}, // 23: command (KEYWORD_FOR) ->  KEYWORD_FOR IDENTIFIER KEYWORD_DO command_list KEYWORD_DONE
     {303, 7}, // 24: command (KEYWORD_FOR) ->  KEYWORD_FOR IDENTIFIER KEYWORD_IF wordholderfirst KEYWORD_DO command_list KEYWORD_DONE
     {303, 5}, // 25: command (KEYWORD_WHILE) ->  KEYWORD_WHILE command_list KEYWORD_DO command_list KEYWORD_DONE
     {303, 5}, // 26: command (KEYWORD_UNTIL) ->  KEYWORD_UNTIL command_list KEYWORD_DO command_list KEYWORD_DONE
     {303, 5}, // 27: command (KEYWORD_CASE) ->  KEYWORD_CASE IDENTIFIER KEYWORD_IN case_partholderfirst KEYWORD_ESAC
     {303, 6}, // 28: command (KEYWORD_IF) ->  KEYWORD_IF command_list KEYWORD_THEN command_list else_part KEYWORD_FI
     {304, 2}, // 29: wordholderfirst (IDENTIFIER) ->  wordholder IDENTIFIER
     {307, 2}, // 30: wordholder (IDENTIFIER) ->  wordholder IDENTIFIER
     {307, 0}, // 31: wordholder ->  <empty>
     {305, 2}, // 32: case_partholderfirst ->  case_partholder case_part
     {308, 2}, // 33: case_partholder ->  case_partholder case_part
     {308, 0}, // 34: case_partholder ->  <empty>
     {310, 1}, // 35: pipeline ->  command
     {310, 3}, // 36: pipeline (PIPE_SYMBOL) ->  pipeline PIPE_SYMBOL command
     {311, 1}, // 37: andor ->  pipeline
     {311, 3}, // 38: andor (ANDF_SYMBOL) ->  andor ANDF_SYMBOL pipeline
     {311, 3}, // 39: andor (ORF_SYMBOL) ->  andor ORF_SYMBOL pipeline
     {298, 1}, // 40: command_list ->  andor
     {298, 2}, // 41: command_list (COMMAND_SEPARATOR) ->  command_list COMMAND_SEPARATOR
     {298, 2}, // 42: command_list (BACKGROUND_COMMANDS) ->  command_list BACKGROUND_COMMANDS
     {298, 3}, // 43: command_list (COMMAND_SEPARATOR) ->  command_list COMMAND_SEPARATOR andor
     {298, 3}, // 44: command_list (BACKGROUND_COMMANDS) ->  command_list BACKGROUND_COMMANDS andor
     {300, 2}, // 45: input_output (OUTPUT_CREATION) ->  OUTPUT_CREATION file
     {300, 2}, // 46: input_output (INPUT_REDIRECTION) ->  INPUT_REDIRECTION file
     {300, 2}, // 47: input_output (OUTPUT_APPEND) ->  OUTPUT_APPEND IDENTIFIER
     {300, 2}, // 48: input_output (INPUT_FROM_A_HERE_DOCUMENT) ->  INPUT_FROM_A_HERE_DOCUMENT IDENTIFIER
     {312, 1}, // 49: file (IDENTIFIER) ->  IDENTIFIER
     {312, 2}, // 50: file (BACKGROUND_COMMANDS) ->  BACKGROUND_COMMANDS INTEGER
     {312, 2}, // 51: file (BACKGROUND_COMMANDS) ->  BACKGROUND_COMMANDS OPERATOR_MINUS
     {309, 4}, // 52: case_part (CCURLY) ->  pattern CCURLY command_list CASE_DELIMITER
     {313, 1}, // 53: pattern (IDENTIFIER) ->  IDENTIFIER
     {313, 3}, // 54: pattern (PIPE_SYMBOL) ->  pattern PIPE_SYMBOL IDENTIFIER
     {306, 5}, // 55: else_part (KEYWORD_ELIF) ->  KEYWORD_ELIF command_list KEYWORD_THEN command_list else_part
     {306, 2}, // 56: else_part (KEYWORD_ELSE) ->  KEYWORD_ELSE command_list
     {306, 0}, // 57: else_part ->  <empty>
     {314, 1}, // 58: start_$ ->  start
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 21} },                              
    { {       297}, {  1} }, // start                     
    { {       298}, {  2} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {        2} }, 
    { {     EOF__}, { ACCEPT__} }, 
    { {         0}, {        0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {  3} },                       
    { {     275}, { 21} }, // COMMAND_SEPARATOR  
    { {     277}, { 22} }, // BACKGROUND_COMMANDS
    { {       0}, { -1} },                       
};

SR__ s_3[] =
{
    { { REQ_DEF}, {   3} },               
    { {     273}, {  23} }, // ANDF_SYMBOL
    { {     274}, {  24} }, // ORF_SYMBOL 
    { {       0}, { -40} },               
};

SR__ s_4[] =
{
    { { REQ_DEF}, {   2} },               
    { {     272}, {  25} }, // PIPE_SYMBOL
    { {       0}, { -37} },               
};

SR__ s_5[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_6[] =
{
    { { REQ_DEF}, {   8} },                              
    { {     299}, {  26} }, // item                      
    { {     288}, {  15} }, // IDENTIFIER                
    { {     300}, {  16} }, // input_output              
    { {     282}, {  17} }, // OUTPUT_CREATION           
    { {     280}, {  18} }, // INPUT_REDIRECTION         
    { {     283}, {  19} }, // OUTPUT_APPEND             
    { {     281}, {  20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       0}, { -20} },                              
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, { 20} },                              
    { {       298}, { 27} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, { 20} },                              
    { {       298}, { 28} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       288}, { 29} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, { 20} },                              
    { {       298}, { 30} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, { 20} },                              
    { {       298}, { 31} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       288}, { 32} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, { 20} },                              
    { {       298}, { 33} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_15[] =
{
    { { REQ_DEF}, {  2} },                   
    { {     289}, { 34} }, // OPERATOR_LET_BE
    { {       0}, { -2} },                   
};

SR__ s_16[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  4} },                       
    { {       312}, { 35} }, // file               
    { {       288}, { 36} }, // IDENTIFIER         
    { {       277}, { 37} }, // BACKGROUND_COMMANDS
    { {         0}, {  0} },                       
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  4} },                       
    { {       312}, { 38} }, // file               
    { {       288}, { 36} }, // IDENTIFIER         
    { {       277}, { 37} }, // BACKGROUND_COMMANDS
    { {         0}, {  0} },                       
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       288}, { 39} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       288}, { 40} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_21[] =
{
    { { REQ_DEF}, {  19} },                              
    { {     311}, {  41} }, // andor                     
    { {     310}, {   4} }, // pipeline                  
    { {     303}, {   5} }, // command                   
    { {     302}, {   6} }, // simple_command            
    { {     278}, {   7} }, // OPARENTHESIS              
    { {     270}, {   8} }, // OCURLY                    
    { {     265}, {   9} }, // KEYWORD_FOR               
    { {     266}, {  10} }, // KEYWORD_WHILE             
    { {     267}, {  11} }, // KEYWORD_UNTIL             
    { {     262}, {  12} }, // KEYWORD_CASE              
    { {     257}, {  13} }, // KEYWORD_IF                
    { {     299}, {  14} }, // item                      
    { {     288}, {  15} }, // IDENTIFIER                
    { {     300}, {  16} }, // input_output              
    { {     282}, {  17} }, // OUTPUT_CREATION           
    { {     280}, {  18} }, // INPUT_REDIRECTION         
    { {     283}, {  19} }, // OUTPUT_APPEND             
    { {     281}, {  20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       0}, { -41} },                              
};

SR__ s_22[] =
{
    { { REQ_DEF}, {  19} },                              
    { {     311}, {  42} }, // andor                     
    { {     310}, {   4} }, // pipeline                  
    { {     303}, {   5} }, // command                   
    { {     302}, {   6} }, // simple_command            
    { {     278}, {   7} }, // OPARENTHESIS              
    { {     270}, {   8} }, // OCURLY                    
    { {     265}, {   9} }, // KEYWORD_FOR               
    { {     266}, {  10} }, // KEYWORD_WHILE             
    { {     267}, {  11} }, // KEYWORD_UNTIL             
    { {     262}, {  12} }, // KEYWORD_CASE              
    { {     257}, {  13} }, // KEYWORD_IF                
    { {     299}, {  14} }, // item                      
    { {     288}, {  15} }, // IDENTIFIER                
    { {     300}, {  16} }, // input_output              
    { {     282}, {  17} }, // OUTPUT_CREATION           
    { {     280}, {  18} }, // INPUT_REDIRECTION         
    { {     283}, {  19} }, // OUTPUT_APPEND             
    { {     281}, {  20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {       0}, { -42} },                              
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, { 18} },                              
    { {       310}, { 43} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, { 18} },                              
    { {       310}, { 44} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, { 17} },                              
    { {       303}, { 45} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_26[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, {  4} },                       
    { {       279}, { 46} }, // CPARENTHESIS       
    { {       275}, { 21} }, // COMMAND_SEPARATOR  
    { {       277}, { 22} }, // BACKGROUND_COMMANDS
    { {         0}, {  0} },                       
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, {  4} },                       
    { {       271}, { 47} }, // CCURLY             
    { {       275}, { 21} }, // COMMAND_SEPARATOR  
    { {       277}, { 22} }, // BACKGROUND_COMMANDS
    { {         0}, {  0} },                       
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  3} },              
    { {       268}, { 48} }, // KEYWORD_DO
    { {       257}, { 49} }, // KEYWORD_IF
    { {         0}, {  0} },              
};

SR__ s_30[] =
{
    { { REQ_TOKEN}, {  4} },                       
    { {       268}, { 50} }, // KEYWORD_DO         
    { {       275}, { 21} }, // COMMAND_SEPARATOR  
    { {       277}, { 22} }, // BACKGROUND_COMMANDS
    { {         0}, {  0} },                       
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  4} },                       
    { {       268}, { 51} }, // KEYWORD_DO         
    { {       275}, { 21} }, // COMMAND_SEPARATOR  
    { {       277}, { 22} }, // BACKGROUND_COMMANDS
    { {         0}, {  0} },                       
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       263}, { 52} }, // KEYWORD_IN
    { {         0}, {  0} },              
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  4} },                       
    { {       258}, { 53} }, // KEYWORD_THEN       
    { {       275}, { 21} }, // COMMAND_SEPARATOR  
    { {       277}, { 22} }, // BACKGROUND_COMMANDS
    { {         0}, {  0} },                       
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       301}, { 54} }, // value       
    { {       278}, { 55} }, // OPARENTHESIS
    { {       286}, { 56} }, // FLOAT       
    { {       287}, { 57} }, // INTEGER     
    { {       284}, { 58} }, // SINGLEQUOTE 
    { {       285}, { 59} }, // DOUBLEQUOTE 
    { {       288}, { 60} }, // IDENTIFIER  
    { {         0}, {  0} },                
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  3} },                  
    { {       287}, { 61} }, // INTEGER       
    { {       292}, { 62} }, // OPERATOR_MINUS
    { {         0}, {  0} },                  
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_41[] =
{
    { { REQ_DEF}, {   3} },               
    { {     273}, {  23} }, // ANDF_SYMBOL
    { {     274}, {  24} }, // ORF_SYMBOL 
    { {       0}, { -43} },               
};

SR__ s_42[] =
{
    { { REQ_DEF}, {   3} },               
    { {     273}, {  23} }, // ANDF_SYMBOL
    { {     274}, {  24} }, // ORF_SYMBOL 
    { {       0}, { -44} },               
};

SR__ s_43[] =
{
    { { REQ_DEF}, {   2} },               
    { {     272}, {  25} }, // PIPE_SYMBOL
    { {       0}, { -38} },               
};

SR__ s_44[] =
{
    { { REQ_DEF}, {   2} },               
    { {     272}, {  25} }, // PIPE_SYMBOL
    { {       0}, { -39} },               
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, { 20} },                              
    { {       298}, { 63} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_49[] =
{
    { { DEF_RED}, {   3} },                   
    { {     304}, {  64} }, // wordholderfirst
    { {     307}, {  65} }, // wordholder     
    { {       0}, { -31} },                   
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 20} },                              
    { {       298}, { 66} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, { 20} },                              
    { {       298}, { 67} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_52[] =
{
    { { DEF_RED}, {   3} },                        
    { {     305}, {  68} }, // case_partholderfirst
    { {     308}, {  69} }, // case_partholder     
    { {       0}, { -34} },                        
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 20} },                              
    { {       298}, { 70} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_54[] =
{
    { { REQ_DEF}, {  8} },                           
    { {     291}, { 71} }, // OPERATOR_PLUS          
    { {     292}, { 72} }, // OPERATOR_MINUS         
    { {     293}, { 73} }, // OPERATOR_MULTIPLICATION
    { {     294}, { 74} }, // OPERATOR_DIVISION      
    { {     296}, { 75} }, // OPERATOR_POWER         
    { {     295}, { 76} }, // OPERATOR_MODULO        
    { {     290}, { 77} }, // OPERATOR_EQUALS        
    { {       0}, { -4} },                           
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       301}, { 78} }, // value       
    { {       278}, { 55} }, // OPARENTHESIS
    { {       286}, { 56} }, // FLOAT       
    { {       287}, { 57} }, // INTEGER     
    { {       284}, { 58} }, // SINGLEQUOTE 
    { {       285}, { 59} }, // DOUBLEQUOTE 
    { {       288}, { 60} }, // IDENTIFIER  
    { {         0}, {  0} },                
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -51} }, 
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  4} },                       
    { {       269}, { 79} }, // KEYWORD_DONE       
    { {       275}, { 21} }, // COMMAND_SEPARATOR  
    { {       277}, { 22} }, // BACKGROUND_COMMANDS
    { {         0}, {  0} },                       
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       268}, { 80} }, // KEYWORD_DO
    { {         0}, {  0} },              
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  2} },              
    { {       288}, { 81} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, {  4} },                       
    { {       269}, { 82} }, // KEYWORD_DONE       
    { {       275}, { 21} }, // COMMAND_SEPARATOR  
    { {       277}, { 22} }, // BACKGROUND_COMMANDS
    { {         0}, {  0} },                       
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, {  4} },                       
    { {       269}, { 83} }, // KEYWORD_DONE       
    { {       275}, { 21} }, // COMMAND_SEPARATOR  
    { {       277}, { 22} }, // BACKGROUND_COMMANDS
    { {         0}, {  0} },                       
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       264}, { 84} }, // KEYWORD_ESAC
    { {         0}, {  0} },                
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  4} },              
    { {       309}, { 85} }, // case_part 
    { {       313}, { 86} }, // pattern   
    { {       288}, { 87} }, // IDENTIFIER
    { {         0}, {  0} },              
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   6} },                       
    { {     306}, {  88} }, // else_part          
    { {     275}, {  21} }, // COMMAND_SEPARATOR  
    { {     277}, {  22} }, // BACKGROUND_COMMANDS
    { {     260}, {  89} }, // KEYWORD_ELIF       
    { {     259}, {  90} }, // KEYWORD_ELSE       
    { {       0}, { -57} },                       
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       301}, { 91} }, // value       
    { {       278}, { 55} }, // OPARENTHESIS
    { {       286}, { 56} }, // FLOAT       
    { {       287}, { 57} }, // INTEGER     
    { {       284}, { 58} }, // SINGLEQUOTE 
    { {       285}, { 59} }, // DOUBLEQUOTE 
    { {       288}, { 60} }, // IDENTIFIER  
    { {         0}, {  0} },                
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       301}, { 92} }, // value       
    { {       278}, { 55} }, // OPARENTHESIS
    { {       286}, { 56} }, // FLOAT       
    { {       287}, { 57} }, // INTEGER     
    { {       284}, { 58} }, // SINGLEQUOTE 
    { {       285}, { 59} }, // DOUBLEQUOTE 
    { {       288}, { 60} }, // IDENTIFIER  
    { {         0}, {  0} },                
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       301}, { 93} }, // value       
    { {       278}, { 55} }, // OPARENTHESIS
    { {       286}, { 56} }, // FLOAT       
    { {       287}, { 57} }, // INTEGER     
    { {       284}, { 58} }, // SINGLEQUOTE 
    { {       285}, { 59} }, // DOUBLEQUOTE 
    { {       288}, { 60} }, // IDENTIFIER  
    { {         0}, {  0} },                
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       301}, { 94} }, // value       
    { {       278}, { 55} }, // OPARENTHESIS
    { {       286}, { 56} }, // FLOAT       
    { {       287}, { 57} }, // INTEGER     
    { {       284}, { 58} }, // SINGLEQUOTE 
    { {       285}, { 59} }, // DOUBLEQUOTE 
    { {       288}, { 60} }, // IDENTIFIER  
    { {         0}, {  0} },                
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       301}, { 95} }, // value       
    { {       278}, { 55} }, // OPARENTHESIS
    { {       286}, { 56} }, // FLOAT       
    { {       287}, { 57} }, // INTEGER     
    { {       284}, { 58} }, // SINGLEQUOTE 
    { {       285}, { 59} }, // DOUBLEQUOTE 
    { {       288}, { 60} }, // IDENTIFIER  
    { {         0}, {  0} },                
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       301}, { 96} }, // value       
    { {       278}, { 55} }, // OPARENTHESIS
    { {       286}, { 56} }, // FLOAT       
    { {       287}, { 57} }, // INTEGER     
    { {       284}, { 58} }, // SINGLEQUOTE 
    { {       285}, { 59} }, // DOUBLEQUOTE 
    { {       288}, { 60} }, // IDENTIFIER  
    { {         0}, {  0} },                
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  8} },                
    { {       301}, { 97} }, // value       
    { {       278}, { 55} }, // OPARENTHESIS
    { {       286}, { 56} }, // FLOAT       
    { {       287}, { 57} }, // INTEGER     
    { {       284}, { 58} }, // SINGLEQUOTE 
    { {       285}, { 59} }, // DOUBLEQUOTE 
    { {       288}, { 60} }, // IDENTIFIER  
    { {         0}, {  0} },                
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {  9} },                           
    { {       279}, { 98} }, // CPARENTHESIS           
    { {       291}, { 71} }, // OPERATOR_PLUS          
    { {       292}, { 72} }, // OPERATOR_MINUS         
    { {       293}, { 73} }, // OPERATOR_MULTIPLICATION
    { {       294}, { 74} }, // OPERATOR_DIVISION      
    { {       296}, { 75} }, // OPERATOR_POWER         
    { {       295}, { 76} }, // OPERATOR_MODULO        
    { {       290}, { 77} }, // OPERATOR_EQUALS        
    { {         0}, {  0} },                           
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, { 20} },                              
    { {       298}, { 99} }, // command_list              
    { {       311}, {  3} }, // andor                     
    { {       310}, {  4} }, // pipeline                  
    { {       303}, {  5} }, // command                   
    { {       302}, {  6} }, // simple_command            
    { {       278}, {  7} }, // OPARENTHESIS              
    { {       270}, {  8} }, // OCURLY                    
    { {       265}, {  9} }, // KEYWORD_FOR               
    { {       266}, { 10} }, // KEYWORD_WHILE             
    { {       267}, { 11} }, // KEYWORD_UNTIL             
    { {       262}, { 12} }, // KEYWORD_CASE              
    { {       257}, { 13} }, // KEYWORD_IF                
    { {       299}, { 14} }, // item                      
    { {       288}, { 15} }, // IDENTIFIER                
    { {       300}, { 16} }, // input_output              
    { {       282}, { 17} }, // OUTPUT_CREATION           
    { {       280}, { 18} }, // INPUT_REDIRECTION         
    { {       283}, { 19} }, // OUTPUT_APPEND             
    { {       281}, { 20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {  0} },                              
};

SR__ s_81[] =
{
    { { REQ_DEF}, {   2} },              
    { {     268}, { -29} }, // KEYWORD_DO
    { {       0}, { -30} },              
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_85[] =
{
    { { REQ_DEF}, {   2} },                
    { {     264}, { -32} }, // KEYWORD_ESAC
    { {       0}, { -33} },                
};

SR__ s_86[] =
{
    { { REQ_TOKEN}, {   3} },               
    { {       271}, { 100} }, // CCURLY     
    { {       272}, { 101} }, // PIPE_SYMBOL
    { {         0}, {   0} },               
};

SR__ s_87[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -53} }, 
};

SR__ s_88[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       261}, { 102} }, // KEYWORD_FI
    { {         0}, {   0} },              
};

SR__ s_89[] =
{
    { { REQ_TOKEN}, {  20} },                              
    { {       298}, { 103} }, // command_list              
    { {       311}, {   3} }, // andor                     
    { {       310}, {   4} }, // pipeline                  
    { {       303}, {   5} }, // command                   
    { {       302}, {   6} }, // simple_command            
    { {       278}, {   7} }, // OPARENTHESIS              
    { {       270}, {   8} }, // OCURLY                    
    { {       265}, {   9} }, // KEYWORD_FOR               
    { {       266}, {  10} }, // KEYWORD_WHILE             
    { {       267}, {  11} }, // KEYWORD_UNTIL             
    { {       262}, {  12} }, // KEYWORD_CASE              
    { {       257}, {  13} }, // KEYWORD_IF                
    { {       299}, {  14} }, // item                      
    { {       288}, {  15} }, // IDENTIFIER                
    { {       300}, {  16} }, // input_output              
    { {       282}, {  17} }, // OUTPUT_CREATION           
    { {       280}, {  18} }, // INPUT_REDIRECTION         
    { {       283}, {  19} }, // OUTPUT_APPEND             
    { {       281}, {  20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {   0} },                              
};

SR__ s_90[] =
{
    { { REQ_TOKEN}, {  20} },                              
    { {       298}, { 104} }, // command_list              
    { {       311}, {   3} }, // andor                     
    { {       310}, {   4} }, // pipeline                  
    { {       303}, {   5} }, // command                   
    { {       302}, {   6} }, // simple_command            
    { {       278}, {   7} }, // OPARENTHESIS              
    { {       270}, {   8} }, // OCURLY                    
    { {       265}, {   9} }, // KEYWORD_FOR               
    { {       266}, {  10} }, // KEYWORD_WHILE             
    { {       267}, {  11} }, // KEYWORD_UNTIL             
    { {       262}, {  12} }, // KEYWORD_CASE              
    { {       257}, {  13} }, // KEYWORD_IF                
    { {       299}, {  14} }, // item                      
    { {       288}, {  15} }, // IDENTIFIER                
    { {       300}, {  16} }, // input_output              
    { {       282}, {  17} }, // OUTPUT_CREATION           
    { {       280}, {  18} }, // INPUT_REDIRECTION         
    { {       283}, {  19} }, // OUTPUT_APPEND             
    { {       281}, {  20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {   0} },                              
};

SR__ s_91[] =
{
    { { REQ_DEF}, {  5} },                           
    { {     293}, { 73} }, // OPERATOR_MULTIPLICATION
    { {     294}, { 74} }, // OPERATOR_DIVISION      
    { {     296}, { 75} }, // OPERATOR_POWER         
    { {     295}, { 76} }, // OPERATOR_MODULO        
    { {       0}, { -5} },                           
};

SR__ s_92[] =
{
    { { REQ_DEF}, {  5} },                           
    { {     293}, { 73} }, // OPERATOR_MULTIPLICATION
    { {     294}, { 74} }, // OPERATOR_DIVISION      
    { {     296}, { 75} }, // OPERATOR_POWER         
    { {     295}, { 76} }, // OPERATOR_MODULO        
    { {       0}, { -6} },                           
};

SR__ s_93[] =
{
    { { REQ_DEF}, {  2} },                  
    { {     296}, { 75} }, // OPERATOR_POWER
    { {       0}, { -7} },                  
};

SR__ s_94[] =
{
    { { REQ_DEF}, {  2} },                  
    { {     296}, { 75} }, // OPERATOR_POWER
    { {       0}, { -8} },                  
};

SR__ s_95[] =
{
    { { REQ_DEF}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_96[] =
{
    { { REQ_DEF}, {   2} },                  
    { {     296}, {  75} }, // OPERATOR_POWER
    { {       0}, { -10} },                  
};

SR__ s_97[] =
{
    { { REQ_DEF}, {   7} },                           
    { {     291}, {  71} }, // OPERATOR_PLUS          
    { {     292}, {  72} }, // OPERATOR_MINUS         
    { {     293}, {  73} }, // OPERATOR_MULTIPLICATION
    { {     294}, {  74} }, // OPERATOR_DIVISION      
    { {     296}, {  75} }, // OPERATOR_POWER         
    { {     295}, {  76} }, // OPERATOR_MODULO        
    { {       0}, { -11} },                           
};

SR__ s_98[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {   4} },                       
    { {       269}, { 105} }, // KEYWORD_DONE       
    { {       275}, {  21} }, // COMMAND_SEPARATOR  
    { {       277}, {  22} }, // BACKGROUND_COMMANDS
    { {         0}, {   0} },                       
};

SR__ s_100[] =
{
    { { REQ_TOKEN}, {  20} },                              
    { {       298}, { 106} }, // command_list              
    { {       311}, {   3} }, // andor                     
    { {       310}, {   4} }, // pipeline                  
    { {       303}, {   5} }, // command                   
    { {       302}, {   6} }, // simple_command            
    { {       278}, {   7} }, // OPARENTHESIS              
    { {       270}, {   8} }, // OCURLY                    
    { {       265}, {   9} }, // KEYWORD_FOR               
    { {       266}, {  10} }, // KEYWORD_WHILE             
    { {       267}, {  11} }, // KEYWORD_UNTIL             
    { {       262}, {  12} }, // KEYWORD_CASE              
    { {       257}, {  13} }, // KEYWORD_IF                
    { {       299}, {  14} }, // item                      
    { {       288}, {  15} }, // IDENTIFIER                
    { {       300}, {  16} }, // input_output              
    { {       282}, {  17} }, // OUTPUT_CREATION           
    { {       280}, {  18} }, // INPUT_REDIRECTION         
    { {       283}, {  19} }, // OUTPUT_APPEND             
    { {       281}, {  20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {   0} },                              
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {   2} },              
    { {       288}, { 107} }, // IDENTIFIER
    { {         0}, {   0} },              
};

SR__ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {   4} },                       
    { {       258}, { 108} }, // KEYWORD_THEN       
    { {       275}, {  21} }, // COMMAND_SEPARATOR  
    { {       277}, {  22} }, // BACKGROUND_COMMANDS
    { {         0}, {   0} },                       
};

SR__ s_104[] =
{
    { { REQ_DEF}, {   3} },                       
    { {     275}, {  21} }, // COMMAND_SEPARATOR  
    { {     277}, {  22} }, // BACKGROUND_COMMANDS
    { {       0}, { -56} },                       
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_106[] =
{
    { { REQ_TOKEN}, {   4} },                       
    { {       276}, { 109} }, // CASE_DELIMITER     
    { {       275}, {  21} }, // COMMAND_SEPARATOR  
    { {       277}, {  22} }, // BACKGROUND_COMMANDS
    { {         0}, {   0} },                       
};

SR__ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -54} }, 
};

SR__ s_108[] =
{
    { { REQ_TOKEN}, {  20} },                              
    { {       298}, { 110} }, // command_list              
    { {       311}, {   3} }, // andor                     
    { {       310}, {   4} }, // pipeline                  
    { {       303}, {   5} }, // command                   
    { {       302}, {   6} }, // simple_command            
    { {       278}, {   7} }, // OPARENTHESIS              
    { {       270}, {   8} }, // OCURLY                    
    { {       265}, {   9} }, // KEYWORD_FOR               
    { {       266}, {  10} }, // KEYWORD_WHILE             
    { {       267}, {  11} }, // KEYWORD_UNTIL             
    { {       262}, {  12} }, // KEYWORD_CASE              
    { {       257}, {  13} }, // KEYWORD_IF                
    { {       299}, {  14} }, // item                      
    { {       288}, {  15} }, // IDENTIFIER                
    { {       300}, {  16} }, // input_output              
    { {       282}, {  17} }, // OUTPUT_CREATION           
    { {       280}, {  18} }, // INPUT_REDIRECTION         
    { {       283}, {  19} }, // OUTPUT_APPEND             
    { {       281}, {  20} }, // INPUT_FROM_A_HERE_DOCUMENT
    { {         0}, {   0} },                              
};

SR__ s_109[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -52} }, 
};

SR__ s_110[] =
{
    { { REQ_DEF}, {   6} },                       
    { {     306}, { 111} }, // else_part          
    { {     275}, {  21} }, // COMMAND_SEPARATOR  
    { {     277}, {  22} }, // BACKGROUND_COMMANDS
    { {     260}, {  89} }, // KEYWORD_ELIF       
    { {     259}, {  90} }, // KEYWORD_ELSE       
    { {       0}, { -57} },                       
};

SR__ s_111[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -55} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved__::UNDETERMINED__),
    // $insert baseclasscode
    d_requiredTokens__(0)
{
}

// base/clearin
void ParserBase::clearin__()
{
    d_nErrors__ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    d_token = Reserved__::UNDETERMINED__;
    d_next = TokenPair{ Reserved__::UNDETERMINED__, STYPE__{} };
    d_recovery = false;
    d_acceptedTokens__ = d_requiredTokens__;
    d_val__ = STYPE__{};

    push__(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

// base/lex
void ParserBase::lex__(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved__::EOF__;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup__() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR__ const *sr = s_state[d_state];
    SR__ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

}

// base/poptoken
void ParserBase::popToken__()
{
    d_token = d_next.first;
    d_val__ = std::move(d_next.second);

    d_next.first = Reserved__::UNDETERMINED__;
}

// base/push
void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize__() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack.resize(newSize);
    }

    ++d_stackIdx;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val__) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken__(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val__) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken__()
{
    if (d_token != Reserved__::UNDETERMINED__)
        pushToken__(d_token);
}

// base/reduce
void ParserBase::reduce__(int rule)
{
    PI__ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop__(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift__(int action)
{
    push__(action);
    popToken__();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens__ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery__()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken__(Reserved__::errTok__);      // specify errTok__ as next token
    push__(lookup__());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top__() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery__()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle__ for details.

    startRecovery__();
}

// derived/executeaction
void Parser::executeAction__(int production)
try
{
    if (token__() != Reserved__::UNDETERMINED__)
        pushToken__(token__());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 51 "grammar"
        {
         std::cout << "command_list" << std::endl;
         }
        break;

        case 2:
#line 58 "grammar"
        {
         std::cout << "identifier" << std::endl;
         }
        break;

        case 3:
#line 63 "grammar"
        {
         std::cout << "input_output" << std::endl;
         }
        break;

        case 4:
#line 68 "grammar"
        {
         std::cout << "= value" << std::endl;
         }
        break;

        case 5:
#line 75 "grammar"
        {
         std::cout << "value + value" << std::endl;
         d_val__ = vs__(-2) + vs__(0);
         std::cout << d_val__ << " az osszeg" << std::endl;
         }
        break;

        case 6:
#line 82 "grammar"
        {
         std::cout << "value - value" << std::endl;
         }
        break;

        case 7:
#line 87 "grammar"
        {
         std::cout << "value * value" << std::endl;
         }
        break;

        case 8:
#line 92 "grammar"
        {
         std::cout << "value / value" << std::endl;
         }
        break;

        case 9:
#line 97 "grammar"
        {
         std::cout << "value ^ value" << std::endl;
         }
        break;

        case 10:
#line 102 "grammar"
        {
         std::cout << "value % value" << std::endl;
         }
        break;

        case 11:
#line 107 "grammar"
        {
         std::cout << "value == value" << std::endl;
         }
        break;

        case 12:
#line 112 "grammar"
        {
         std::cout << "( value )" << std::endl;
         }
        break;

        case 13:
#line 117 "grammar"
        {
         std::cout << "float" << std::endl;
         }
        break;

        case 14:
#line 122 "grammar"
        {
         std::cout << "integer" << std::endl;
         }
        break;

        case 15:
#line 127 "grammar"
        {
         std::cout << "singlequote" << std::endl;
         }
        break;

        case 16:
#line 132 "grammar"
        {
         std::cout << "doublequote" << std::endl;
         }
        break;

        case 17:
#line 137 "grammar"
        {
         std::cout << "identifier" << std::endl;
         }
        break;

        case 18:
#line 144 "grammar"
        {
         std::cout << "item" << std::endl;
         }
        break;

        case 19:
#line 149 "grammar"
        {
         std::cout << "simple_command item" << std::endl;
         }
        break;

        case 20:
#line 156 "grammar"
        {
         std::cout << "simple_command" << std::endl;
         }
        break;

        case 21:
#line 161 "grammar"
        {
         std::cout << "OPARENTHESIS command_list CPARENTHESIS" << std::endl;
         }
        break;

        case 22:
#line 166 "grammar"
        {
         std::cout << "OCURLY command_list CCURLY" << std::endl;
         }
        break;

        case 23:
#line 171 "grammar"
        {
         std::cout << "KEYWORD_FOR IDENTIFIER KEYWORD_DO command_list KEYWORD_DONE" << std::endl;
         }
        break;

        case 24:
#line 176 "grammar"
        {
         std::cout << "KEYWORD_FOR IDENTIFIER KEYWORD_IF wordholderfirst KEYWORD_DO command_list KEYWORD_DONE" << std::endl;
         }
        break;

        case 25:
#line 181 "grammar"
        {
         std::cout << "KEYWORD_WHILE command_list KEYWORD_DO command_list KEYWORD_DONE" << std::endl;
         }
        break;

        case 26:
#line 186 "grammar"
        {
         std::cout << "KEYWORD_UNTIL command_list KEYWORD_DO command_list KEYWORD_DONE" << std::endl;
         }
        break;

        case 27:
#line 191 "grammar"
        {
         std::cout << "KEYWORD_CASE IDENTIFIER KEYWORD_IN case_partholderfirst KEYWORD_ESAC" << std::endl;
         }
        break;

        case 28:
#line 196 "grammar"
        {
         std::cout << "KEYWORD_IF command_list KEYWORD_THEN command_list else_part KEYWORD_FI" << std::endl;
         }
        break;

        case 29:
#line 203 "grammar"
        {
         std::cout << "wordholder IDENTIFIER" << std::endl;
         }
        break;

        case 30:
#line 210 "grammar"
        {
         std::cout << "wordholder IDENTIFIER" << std::endl;
         }
        break;

        case 31:
#line 215 "grammar"
        {
         std::cout << "empty" << std::endl;
         }
        break;

        case 32:
#line 222 "grammar"
        {
         std::cout << "case_partholder case_part" << std::endl;
         }
        break;

        case 33:
#line 229 "grammar"
        {
         std::cout << "case_partholder case_part" << std::endl;
         }
        break;

        case 34:
#line 234 "grammar"
        {
         std::cout << "empty" << std::endl;
         }
        break;

        case 35:
#line 242 "grammar"
        {
         std::cout << "command" << std::endl;
         }
        break;

        case 36:
#line 247 "grammar"
        {
         std::cout << "pipeline PIPE_SYMBOL command" << std::endl;
         }
        break;

        case 37:
#line 254 "grammar"
        {
         std::cout << "pipeline" << std::endl;
         }
        break;

        case 38:
#line 259 "grammar"
        {
         std::cout << "andor ANDF_SYMBOL pipeline" << std::endl;
         }
        break;

        case 39:
#line 264 "grammar"
        {
         std::cout << "andor ORF_SYMBOL pipeline" << std::endl;
         }
        break;

        case 40:
#line 271 "grammar"
        {
         std::cout << "andor" << std::endl;
         }
        break;

        case 41:
#line 276 "grammar"
        {
         std::cout << "command_list COMMAND_SEPARATOR" << std::endl;
         }
        break;

        case 42:
#line 281 "grammar"
        {
         std::cout << "command_list BACKGROUND_COMMANDS" << std::endl;
         }
        break;

        case 43:
#line 286 "grammar"
        {
         std::cout << "command_list COMMAND_SEPARATOR andor" << std::endl;
         }
        break;

        case 44:
#line 291 "grammar"
        {
         std::cout << "command_list BACKGROUND_COMMANDS andor" << std::endl;
         }
        break;

        case 45:
#line 298 "grammar"
        {
         std::cout << "OUTPUT_APPEND file" << std::endl;
         }
        break;

        case 46:
#line 303 "grammar"
        {
         std::cout << "INPUT_REDIRECTION file" << std::endl;
         }
        break;

        case 47:
#line 308 "grammar"
        {
         std::cout << "OUTPUT_APPEND IDENTIFIER" << std::endl;
         }
        break;

        case 48:
#line 313 "grammar"
        {
         std::cout << "INPUT_FROM_A_HERE_DOCUMENT IDENTIFIER" << std::endl;
         }
        break;

        case 49:
#line 320 "grammar"
        {
         std::cout << "WORD" << std::endl;
         }
        break;

        case 50:
#line 325 "grammar"
        {
         std::cout << "BACKGROUND_COMMANDS INTEGER" << std::endl;
         }
        break;

        case 51:
#line 330 "grammar"
        {
         std::cout << "BACKGROUND_COMMANDS OPERATOR_MINUS" << std::endl;
         }
        break;

        case 52:
#line 337 "grammar"
        {
         std::cout << "pattern CCURLY command_list CASE_DELIMITER" << std::endl;
         }
        break;

        case 53:
#line 344 "grammar"
        {
         std::cout << "WORD" << std::endl;
         }
        break;

        case 54:
#line 349 "grammar"
        {
         std::cout << "pattern PIPE_SYMBOL IDENTIFIER" << std::endl;
         }
        break;

        case 55:
#line 356 "grammar"
        {
         std::cout << "KEYWORD_ELIF command_list KEYWORD_THEN command_list else_part" << std::endl;
         }
        break;

        case 56:
#line 361 "grammar"
        {
         std::cout << "KEYWORD_ELSE command_list" << std::endl;
         }
        break;

        case 57:
#line 366 "grammar"
        {
         std::cout << "empty" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle__()
try
{
    if (s_state[state__()]->d_type & REQ_TOKEN)
        nextToken__();              // obtain next token


    int action = lookup__();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift__(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery__())
            redoToken__();
        else
            executeAction__(-action);
                                            // next token is the rule's LHS
        reduce__(-action); 
        return;
    }

    if (recovery__())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery__)
{
    if (not recovery__())
        errorRecovery__();
    else
    {
        if (token__() == Reserved__::EOF__)
            ABORT();
        popToken__();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken__()
{ 
    // If d_token is Reserved__::UNDETERMINED__ then if savedToken__() is
    // Reserved__::UNDETERMINED__ another token is obtained from lex(). Then
    // savedToken__() is assigned to d_token.

                                    // no need for a token: got one already
    if (token__() != Reserved__::UNDETERMINED__) 
    {
        return;                             
    }

    if (savedToken__() != Reserved__::UNDETERMINED__)
    {
        popToken__();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;       // accept another token (see
                                    // errorRecover())
        lex__(lex());
        print__();
    }
    print();
}

// derived/print
void Parser::print__()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin__.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin__();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle__();
    }
}
catch (Return__ retValue)
{
    return retValue or d_nErrors__;
}


// derived/tail


