// Generated by Bisonc++ V6.00.00 on Sat, 02 Dec 2017 11:53:10 +0000

// base/comment

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token is Reserved__::UNDETERMINED__, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on errTok__
// which is applied. In this errTok__ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
//      }

// base/declarations

namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum Reserved__
    {
        UNDETERMINED__   = -2,
        EOF__            = -1,
        errTok__         = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    enum StateTransition
    {
        ACCEPT__   = 0,     // `ACCEPT' TRANSITION
    };

    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            StateType d_type;
            int       d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {287, 1}, // 1: item (WORD) ->  WORD
     {287, 3}, // 2: item (NAME) ->  NAME ASSIGN value
     {288, 1}, // 3: value (WORD) ->  WORD
     {288, 1}, // 4: value (SINGLEQUOTE) ->  SINGLEQUOTE
     {288, 1}, // 5: value (DOUBLEQUOTE) ->  DOUBLEQUOTE
     {288, 1}, // 6: value (HEXADECIMAL) ->  HEXADECIMAL
     {288, 1}, // 7: value (NUMBER) ->  NUMBER
     {288, 1}, // 8: value (NAME) ->  NAME
     {289, 1}, // 9: simplecommand ->  item
     {289, 2}, // 10: simplecommand ->  simplecommand item
     {290, 1}, // 11: command ->  simplecommand
     {290, 3}, // 12: command (OPARENTHESES) ->  OPARENTHESES commandlist CPARENTHESES
     {290, 3}, // 13: command (OCURLY) ->  OCURLY commandlist CCURLY
     {290, 7}, // 14: command (FOR) ->  FOR NAME IN wordholder DO commandlist DONE
     {290, 5}, // 15: command (WHILE) ->  WHILE commandlist DO commandlist DONE
     {290, 5}, // 16: command (UNTIL) ->  UNTIL commandlist DO commandlist DONE
     {290, 5}, // 17: command (CASE) ->  CASE WORD IN casepartholder ESAC
     {290, 6}, // 18: command (IF) ->  IF commandlist THEN commandlist elsepart FI
     {292, 1}, // 19: wordholder ->  value
     {292, 2}, // 20: wordholder ->  wordholder value
     {293, 1}, // 21: casepartholder ->  casepart
     {293, 2}, // 22: casepartholder ->  casepartholder casepart
     {296, 1}, // 23: pipeline ->  command
     {297, 1}, // 24: andor ->  pipeline
     {297, 3}, // 25: andor (AND) ->  andor AND pipeline
     {297, 3}, // 26: andor (OR) ->  andor OR pipeline
     {291, 4}, // 27: commandlist (SEMICOLON) ->  andor #0001 commandlist SEMICOLON
     {298, 0}, // 28: #0001 ->  <empty>
     {291, 3}, // 29: commandlist (SEMICOLON) ->  commandlist SEMICOLON andor
     {295, 4}, // 30: casepart (CPARENTHESES) ->  pattern CPARENTHESES commandlist DOUBLESEMICOLON
     {299, 5}, // 31: pattern (WORD) ->  WORD #0002 pattern PIPE WORD
     {300, 0}, // 32: #0002 ->  <empty>
     {294, 5}, // 33: elsepart (ELIF) ->  ELIF commandlist THEN commandlist elsepart
     {294, 2}, // 34: elsepart (ELSE) ->  ELSE commandlist
     {294, 1}, // 35: elsepart ->  empty
     {301, 0}, // 36: empty ->  <empty>
     {302, 1}, // 37: command_$ ->  command
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 13} },                 
    { {       290}, {  1} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {        2} }, 
    { {     EOF__}, { ACCEPT__} }, 
    { {         0}, {        0} }, 
};

SR__ s_2[] =
{
    { { REQ_DEF}, {   4} },        
    { {     287}, {  13} }, // item
    { {     274}, {  11} }, // WORD
    { {     275}, {  12} }, // NAME
    { {       0}, { -11} },        
};

SR__ s_3[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 14} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 18} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       275}, { 19} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 20} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 21} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       274}, { 22} }, // WORD
    { {         0}, {  0} },        
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 23} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_11[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       283}, { 24} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_13[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  3} },                
    { {       271}, { 25} }, // CPARENTHESES
    { {       278}, { 26} }, // SEMICOLON   
    { {         0}, {  0} },                
};

SR__ s_15[] =
{
    { { REQ_DEF}, {   4} },         
    { {     298}, {  27} }, // #0001
    { {     280}, {  28} }, // AND  
    { {     281}, {  29} }, // OR   
    { {       0}, { -28} },         
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_18[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       273}, { 30} }, // CCURLY   
    { {       278}, { 26} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       261}, { 31} }, // IN
    { {         0}, {  0} },      
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       258}, { 32} }, // DO       
    { {       278}, { 26} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       258}, { 33} }, // DO       
    { {       278}, { 26} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       261}, { 34} }, // IN
    { {         0}, {  0} },      
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       266}, { 35} }, // THEN     
    { {       278}, { 26} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  8} },               
    { {       288}, { 36} }, // value      
    { {       274}, { 37} }, // WORD       
    { {       284}, { 38} }, // SINGLEQUOTE
    { {       285}, { 39} }, // DOUBLEQUOTE
    { {       286}, { 40} }, // HEXADECIMAL
    { {       276}, { 41} }, // NUMBER     
    { {       275}, { 42} }, // NAME       
    { {         0}, {  0} },               
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, { 15} },                 
    { {       297}, { 43} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 44} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_28[] =
{
    { { REQ_TOKEN}, { 14} },                 
    { {       296}, { 45} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, { 14} },                 
    { {       296}, { 46} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_30[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_31[] =
{
    { { REQ_TOKEN}, {  9} },               
    { {       292}, { 47} }, // wordholder 
    { {       288}, { 48} }, // value      
    { {       274}, { 37} }, // WORD       
    { {       284}, { 38} }, // SINGLEQUOTE
    { {       285}, { 39} }, // DOUBLEQUOTE
    { {       286}, { 40} }, // HEXADECIMAL
    { {       276}, { 41} }, // NUMBER     
    { {       275}, { 42} }, // NAME       
    { {         0}, {  0} },               
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 49} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 50} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  5} },                  
    { {       293}, { 51} }, // casepartholder
    { {       295}, { 52} }, // casepart      
    { {       299}, { 53} }, // pattern       
    { {       274}, { 54} }, // WORD          
    { {         0}, {  0} },                  
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 55} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_36[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -2} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_43[] =
{
    { { REQ_DEF}, {   3} },       
    { {     280}, {  28} }, // AND
    { {     281}, {  29} }, // OR 
    { {       0}, { -29} },       
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },             
    { {       278}, { 56} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_45[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_46[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  9} },               
    { {       258}, { 57} }, // DO         
    { {       288}, { 58} }, // value      
    { {       274}, { 37} }, // WORD       
    { {       284}, { 38} }, // SINGLEQUOTE
    { {       285}, { 39} }, // DOUBLEQUOTE
    { {       286}, { 40} }, // HEXADECIMAL
    { {       276}, { 41} }, // NUMBER     
    { {       275}, { 42} }, // NAME       
    { {         0}, {  0} },               
};

SR__ s_48[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       259}, { 59} }, // DONE     
    { {       278}, { 26} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       259}, { 60} }, // DONE     
    { {       278}, { 26} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  5} },            
    { {       264}, { 61} }, // ESAC    
    { {       295}, { 62} }, // casepart
    { {       299}, { 53} }, // pattern 
    { {       274}, { 54} }, // WORD    
    { {         0}, {  0} },            
};

SR__ s_52[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  2} },                
    { {       271}, { 63} }, // CPARENTHESES
    { {         0}, {  0} },                
};

SR__ s_54[] =
{
    { { DEF_RED}, {   2} },         
    { {     300}, {  64} }, // #0002
    { {       0}, { -32} },         
};

SR__ s_55[] =
{
    { { REQ_DEF}, {   6} },             
    { {     294}, {  65} }, // elsepart 
    { {     278}, {  26} }, // SEMICOLON
    { {     268}, {  66} }, // ELIF     
    { {     269}, {  67} }, // ELSE     
    { {     301}, {  68} }, // empty    
    { {       0}, { -36} },             
};

SR__ s_56[] =
{
    { { REQ_DEF}, {  15} },                 
    { {     297}, {  43} }, // andor        
    { {     296}, {  16} }, // pipeline     
    { {     290}, {  17} }, // command      
    { {     289}, {   2} }, // simplecommand
    { {     270}, {   3} }, // OPARENTHESES 
    { {     272}, {   4} }, // OCURLY       
    { {     257}, {   5} }, // FOR          
    { {     260}, {   6} }, // WHILE        
    { {     262}, {   7} }, // UNTIL        
    { {     263}, {   8} }, // CASE         
    { {     265}, {   9} }, // IF           
    { {     287}, {  10} }, // item         
    { {     274}, {  11} }, // WORD         
    { {     275}, {  12} }, // NAME         
    { {       0}, { -27} },                 
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 69} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_59[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_61[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_62[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 70} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       299}, { 71} }, // pattern
    { {       274}, { 54} }, // WORD   
    { {         0}, {  0} },           
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, {  2} },      
    { {       267}, { 72} }, // FI
    { {         0}, {  0} },      
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 73} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 74} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_68[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       259}, { 75} }, // DONE     
    { {       278}, { 26} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  3} },                   
    { {       279}, { 76} }, // DOUBLESEMICOLON
    { {       278}, { 26} }, // SEMICOLON      
    { {         0}, {  0} },                   
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       282}, { 77} }, // PIPE
    { {         0}, {  0} },        
};

SR__ s_72[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, {  3} },             
    { {       266}, { 78} }, // THEN     
    { {       278}, { 26} }, // SEMICOLON
    { {         0}, {  0} },             
};

SR__ s_74[] =
{
    { { REQ_DEF}, {   2} },             
    { {     278}, {  26} }, // SEMICOLON
    { {       0}, { -34} },             
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       274}, { 79} }, // WORD
    { {         0}, {  0} },        
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, { 16} },                 
    { {       291}, { 80} }, // commandlist  
    { {       297}, { 15} }, // andor        
    { {       296}, { 16} }, // pipeline     
    { {       290}, { 17} }, // command      
    { {       289}, {  2} }, // simplecommand
    { {       270}, {  3} }, // OPARENTHESES 
    { {       272}, {  4} }, // OCURLY       
    { {       257}, {  5} }, // FOR          
    { {       260}, {  6} }, // WHILE        
    { {       262}, {  7} }, // UNTIL        
    { {       263}, {  8} }, // CASE         
    { {       265}, {  9} }, // IF           
    { {       287}, { 10} }, // item         
    { {       274}, { 11} }, // WORD         
    { {       275}, { 12} }, // NAME         
    { {         0}, {  0} },                 
};

SR__ s_79[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_80[] =
{
    { { REQ_DEF}, {   6} },             
    { {     294}, {  81} }, // elsepart 
    { {     278}, {  26} }, // SEMICOLON
    { {     268}, {  66} }, // ELIF     
    { {     269}, {  67} }, // ELSE     
    { {     301}, {  68} }, // empty    
    { {       0}, { -36} },             
};

SR__ s_81[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,
};

} // anonymous namespace ends




// If the parsing function call (i.e., parse()' needs arguments, then provide
// an overloaded function.  The code below doesn't rely on parameters, so no
// arguments are required.  Furthermore, parse uses a function try block to
// allow us to do ACCEPT and ABORT from anywhere, even from within members
// called by actions, simply throwing the appropriate exceptions.


// base/base1
ParserBase::ParserBase()
:
    d_token(Reserved__::UNDETERMINED__),
    // $insert baseclasscode
    d_requiredTokens__(0)
{
}

// base/clearin
void ParserBase::clearin__()
{
    d_nErrors__ = 0;
    d_stackIdx = -1;
    d_stateStack.clear();
    // $insert LTYPEclear
    d_locationStack.clear();
    d_token = Reserved__::UNDETERMINED__;
    d_next = TokenPair{ Reserved__::UNDETERMINED__, STYPE__{} };
    d_recovery = false;
    d_acceptedTokens__ = d_requiredTokens__;
    d_val__ = STYPE__{};

    push__(0);
}

// base/debugfunctions

void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

// base/lex
void ParserBase::lex__(int token)
{
    d_token = token;

    if (d_token <= 0)
        d_token = Reserved__::EOF__;

    d_terminalToken = true;
}

// base/lookup
int ParserBase::lookup__() const
{
    // if the final transition is negative, then we should reduce by the rule
    // given by its positive value.

    SR__ const *sr = s_state[d_state];
    SR__ const *last = sr + sr->d_lastIdx;

    for ( ; ++sr != last; )           // visit all but the last SR entries
    {
        if (sr->d_token == d_token)
            return sr->d_action;
    }

    if (sr == last)   // reached the last element
    {
        if (sr->d_action < 0)   // default reduction
        {
            return sr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = sr->d_action;


    return action;
}

// base/pop
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx -= count;
    d_state = d_stateStack[d_stackIdx].first;
    d_vsp = &d_stateStack[d_stackIdx];

    // $insert LTYPEpop
    d_lsp = &d_locationStack[d_stackIdx];
}

// base/poptoken
void ParserBase::popToken__()
{
    d_token = d_next.first;
    d_val__ = std::move(d_next.second);

    d_next.first = Reserved__::UNDETERMINED__;
}

// base/push
void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack.size();
    if (stackSize__() == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack.resize(newSize);
        // $insert LTYPEresize
        d_locationStack.resize(newSize);
    }

    ++d_stackIdx;
    // $insert LTYPEpush
    *(d_lsp = &d_locationStack[d_stackIdx]) = d_loc__;
    d_stateStack[d_stackIdx] = 
                    StatePair{ d_state = state, std::move(d_val__) };

    d_vsp = &d_stateStack[d_stackIdx];

    if (d_stackIdx == 0)
    {
    }
    else
    {
    }
}

// base/pushtoken
void ParserBase::pushToken__(int token)
{
    d_next = TokenPair{ d_token, std::move(d_val__) };
    d_token = token;
}

// base/redotoken
void ParserBase::redoToken__()
{
    if (d_token != Reserved__::UNDETERMINED__)
        pushToken__(d_token);
}

// base/reduce
void ParserBase::reduce__(int rule)
{
    PI__ const &pi = s_productionInfo[rule];

    d_token = pi.d_nonTerm;
    pop__(pi.d_size);

    d_terminalToken = false;
}

// base/shift
void ParserBase::shift__(int action)
{
    push__(action);
    popToken__();               // token processed

    if (d_recovery and d_terminalToken)
    {
        d_recovery = false;
        d_acceptedTokens__ = 0;
    }
}

// base/startrecovery
void ParserBase::startRecovery__()
{
    int lastToken = d_token;                // give the unexpected token a
                                            // chance to be processed
                                            // again.

    pushToken__(Reserved__::errTok__);      // specify errTok__ as next token
    push__(lookup__());                     // push the error state

    d_token = lastToken;                    // reactivate the unexpected
                                            // token (we're now in an
                                            // ERROR state).

    d_recovery = true;
}

// base/top
inline size_t ParserBase::top__() const
{
    return d_stateStack[d_stackIdx].first;
}

// derived/errorrecovery
void Parser::errorRecovery__()
{
    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)



    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error();                                // simply skip input
    }

    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, looking up a token allows us to proceed.
    // Continuation may be require multiple reductions, but eventually a
    // terminal-token shift is used. See nextCycle__ for details.

    startRecovery__();
}

// derived/executeaction
void Parser::executeAction__(int production)
try
{
    if (token__() != Reserved__::UNDETERMINED__)
        pushToken__(token__());     // save an already available token
    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 56 "command_line.y"
        {
         std::cout << "item->WORD" << std::endl;
         }
        break;

        case 2:
#line 61 "command_line.y"
        {
         std::cout << "item->NAME ASSIGN WORD" << std::endl;
         }
        break;

        case 3:
#line 68 "command_line.y"
        {
         std::cout << "value->WORD" << std::endl;
         }
        break;

        case 4:
#line 73 "command_line.y"
        {
         std::cout << "value->SINGLEQUOTE" << std::endl;
         }
        break;

        case 5:
#line 78 "command_line.y"
        {
         std::cout << "value->DOUBLEQUOTE" << std::endl;
         }
        break;

        case 6:
#line 83 "command_line.y"
        {
         std::cout << "value->HEXADECIMAL" << std::endl;
         }
        break;

        case 7:
#line 88 "command_line.y"
        {
         std::cout << "value->NUMBER" << std::endl;
         }
        break;

        case 8:
#line 93 "command_line.y"
        {
         std::cout << "value -> NAME" << std::endl;
         }
        break;

        case 9:
#line 101 "command_line.y"
        {
         std::cout << "simplecommand -> item" << std::endl;
         }
        break;

        case 10:
#line 106 "command_line.y"
        {
         std::cout << "simplecommand -> simple-command item" << std::endl;
         }
        break;

        case 11:
#line 113 "command_line.y"
        {
         std::cout << "command -> simplecommand" << std::endl;
         }
        break;

        case 12:
#line 118 "command_line.y"
        {
         std::cout << "command -> OPARENTHESES commandlist CPARENTHESES" << std::endl;
         }
        break;

        case 13:
#line 123 "command_line.y"
        {
         std::cout << "command -> OCURLY commandlist CCURLY" << std::endl;
         }
        break;

        case 14:
#line 128 "command_line.y"
        {
         std::cout << "command -> FOR NAME IN wordholder DO commandlist DONE" << std::endl;
         }
        break;

        case 15:
#line 133 "command_line.y"
        {
         std::cout << "command -> WHILE commandlist DO commandlist DONE" << std::endl;
         }
        break;

        case 16:
#line 138 "command_line.y"
        {
         std::cout << "command -> UNTIL commandlist DO commandlist DONE" << std::endl;
         }
        break;

        case 17:
#line 143 "command_line.y"
        {
         std::cout << "command -> CASE WORD IN casepartholder ESAC" << std::endl;
         }
        break;

        case 18:
#line 148 "command_line.y"
        {
         std::cout << "command -> IF commandlist THEN commandlist elsepart FI" << std::endl;
         }
        break;

        case 19:
#line 155 "command_line.y"
        {
         std::cout << "wordholder -> WORD" << std::endl;
         }
        break;

        case 20:
#line 160 "command_line.y"
        {
         std::cout << "wordholder -> wordholder WORD" << std::endl;
         }
        break;

        case 21:
#line 167 "command_line.y"
        {
         std::cout << "casepartholder -> casepart" << std::endl;
         }
        break;

        case 22:
#line 172 "command_line.y"
        {
         std::cout << "casepartholder -> casepartholder casepart" << std::endl;
         }
        break;

        case 23:
#line 179 "command_line.y"
        {
         std::cout << "pipeline -> command" << std::endl;
         }
        break;

        case 24:
#line 186 "command_line.y"
        {
         std::cout << "andor -> pipeline" << std::endl;
         }
        break;

        case 25:
#line 191 "command_line.y"
        {
         std::cout << "andor -> andor AND pipeline" << std::endl;
         }
        break;

        case 26:
#line 196 "command_line.y"
        {
         std::cout << "andor -> andor OR pipeline" << std::endl;
         }
        break;

        case 27:
#line 207 "command_line.y"
        {
         std::cout << "commandlist -> commandlist SEMICOLON" << std::endl;
         }
        break;

        case 28:
#line 203 "command_line.y"
        {
         std::cout << "commandlist -> andor" << std::endl;
         }
        break;

        case 29:
#line 212 "command_line.y"
        {
         std::cout << "commandlist -> commandlist SEMICOLON andor" << std::endl;
         }
        break;

        case 30:
#line 219 "command_line.y"
        {
         std::cout << "casepart -> pattern CPARENTHESES commandlist DOUBLESEMICOLON" << std::endl;
         }
        break;

        case 31:
#line 230 "command_line.y"
        {
         std::cout << "pattern -> pattern PIPE WORD" << std::endl;
         }
        break;

        case 32:
#line 226 "command_line.y"
        {
         std::cout << "pattern -> WORD" << std::endl;
         }
        break;

        case 33:
#line 237 "command_line.y"
        {
         std::cout << "elsepart -> ELIF commandlist THEN commandlist elsepart" << std::endl;
         }
        break;

        case 34:
#line 242 "command_line.y"
        {
         std::cout << "elsepart -> ELSE commandlist" << std::endl;
         }
        break;

        case 35:
#line 247 "command_line.y"
        {
         std::cout << "elsepart -> empty" << std::endl;
         }
        break;

        case 36:
#line 254 "command_line.y"
        {
         std::cout << "empty" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler(exc);
}

// derived/nextcycle
void Parser::nextCycle__()
try
{
    if (s_state[state__()]->d_type & REQ_TOKEN)
        nextToken__();              // obtain next token


    int action = lookup__();        // lookup d_token in d_state

    if (action > 0)                 // SHIFT: push a new state
    {
        shift__(action);
        return;
    }

    if (action < 0)            // REDUCE: execute and pop.
    {

        if (recovery__())
            redoToken__();
        else
            executeAction__(-action);
                                            // next token is the rule's LHS
        reduce__(-action); 
        return;
    }

    if (recovery__())
        ABORT();
    else 
        ACCEPT();
}
catch (ErrorRecovery__)
{
    if (not recovery__())
        errorRecovery__();
    else
    {
        if (token__() == Reserved__::EOF__)
            ABORT();
        popToken__();               // skip the failing token
    }
}


// derived/nexttoken
void Parser::nextToken__()
{ 
    // If d_token is Reserved__::UNDETERMINED__ then if savedToken__() is
    // Reserved__::UNDETERMINED__ another token is obtained from lex(). Then
    // savedToken__() is assigned to d_token.

                                    // no need for a token: got one already
    if (token__() != Reserved__::UNDETERMINED__) 
    {
        return;                             
    }

    if (savedToken__() != Reserved__::UNDETERMINED__)
    {
        popToken__();               // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;       // accept another token (see
                                    // errorRecover())
        lex__(lex());
        print__();
    }
    print();
}

// derived/print
void Parser::print__()
{
// $insert print
}

// derived/parse
int Parser::parse()
try 
{
    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and all relevant variables
    // are initialized by Base::clearin__.
    //
    // Then, in an eternal loop:
    //
    //  1. If a state is a REQ_TOKEN type, then the next token is obtained
    //     from nextToken().  This may very well be the currently available
    //     token. When retrieving a terminal token d_terminal is set to true.
    //
    //  2. lookup() is called, d_token is looked up in the current state's
    //     SR_ array.
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token is not found, and the state has no
    //     default reduction.

    clearin__();                            // initialize, push(0)

    while (true)
    {
// $insert prompt
        nextCycle__();
    }
}
catch (Return__ retValue)
{
    return retValue or d_nErrors__;
}


// derived/tail


