#!/bin/bash

program=`pwd`
program=`basename $program`

case $1 in
(build)
        echo "g++ --std=c++17 -Wall -o test test.cc ../parser/parse.cc ../scanner/lex.cc"
        g++ --std=c++17 -Wall -o test test.cc ../parser/parse.cc ../scanner/lex.cc
    ;;
    (*)
        echo "use
\"./make build\" for build"
    ;;
esac